-- ============================================
-- DROP 테이블 (역순으로 삭제 - 자식 테이블부터)
-- ============================================
DROP TABLE PT_RESERVE CASCADE CONSTRAINTS;
DROP TABLE LOCKER_PASS CASCADE CONSTRAINTS;
DROP TABLE PT_PASS CASCADE CONSTRAINTS;
DROP TABLE MEMBERSHIP CASCADE CONSTRAINTS;
DROP TABLE PURCHASE_ITEM CASCADE CONSTRAINTS;
DROP TABLE SALES CASCADE CONSTRAINTS;  -- PURCHASE, STOCK, GYM 참조
DROP TABLE ATTENDANCE CASCADE CONSTRAINTS;
DROP TABLE INQUIRY_RESERVE CASCADE CONSTRAINTS;
DROP TABLE INBODY_RECORD CASCADE CONSTRAINTS;
DROP TABLE GOAL_MANAGE CASCADE CONSTRAINTS;
DROP TABLE STOCK_MANAGER CASCADE CONSTRAINTS;
DROP TABLE MACHINE_MANAGE CASCADE CONSTRAINTS;
DROP TABLE PURCHASE CASCADE CONSTRAINTS;
DROP TABLE LOCKER CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE GYM_NOTICE CASCADE CONSTRAINTS;
DROP TABLE YOUTUBE_URL CASCADE CONSTRAINTS;
DROP TABLE GYM_DETAIL CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE GYM CASCADE CONSTRAINTS;
DROP TABLE STOCK CASCADE CONSTRAINTS;
DROP TABLE MACHINE CASCADE CONSTRAINTS;
DROP TABLE ATT_CACHE CASCADE CONSTRAINTS;
DROP TABLE GOAL CASCADE CONSTRAINTS;
-- 시퀀스 삭제
DROP SEQUENCE SEQ_GOAL_NO;
DROP SEQUENCE SEQ_ATT_CACHE_NO;
DROP SEQUENCE SEQ_STOCK_ID;
DROP SEQUENCE SEQ_GYM_NO;
DROP SEQUENCE SEQ_GYM_DETAIL_NO;
DROP SEQUENCE SEQ_YOUTUBE_URL_NO;
DROP SEQUENCE SEQ_NOTICE_NO;
DROP SEQUENCE SEQ_MACHINE_NO;
DROP SEQUENCE SEQ_MACHINE_MANAGE_NO;
DROP SEQUENCE SEQ_LOCKER_NO;
DROP SEQUENCE SEQ_STOCK_MANAGE_NO;
DROP SEQUENCE SEQ_PRODUCT_NO;
DROP SEQUENCE SEQ_MNO;
DROP SEQUENCE SEQ_GOAL_MANAGE_NO;
DROP SEQUENCE SEQ_INBODY_NO;
DROP SEQUENCE SEQ_INQUIRY_NO;
DROP SEQUENCE SEQ_ATTENDANCE_NO;
DROP SEQUENCE SEQ_PURCHASE_NO;
DROP SEQUENCE SEQ_PURCHASE_ITEM_NO;
DROP SEQUENCE SEQ_MEMBERSHIP_NO;
DROP SEQUENCE SEQ_PT_PASS_NO;
DROP SEQUENCE SEQ_LOCKER_PASS_NO;
DROP SEQUENCE SEQ_PT_RESERVE_NO;
DROP SEQUENCE SEQ_SALES_NO;
-- ============================================
-- 1단계: 독립 테이블 (부모 테이블)
-- ============================================

-- 1. 운동목표 테이블
CREATE TABLE GOAL (
    GOAL_NO NUMBER NOT NULL,
    GOAL_TITLE VARCHAR2(200) NOT NULL,
    GOAL_STATUS VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_GOAL PRIMARY KEY (GOAL_NO)
);

COMMENT ON COLUMN GOAL.GOAL_NO IS '목표 번호(PK)';
COMMENT ON COLUMN GOAL.GOAL_TITLE IS '목표 제목';
COMMENT ON COLUMN GOAL.GOAL_STATUS IS '목표 상태("달성","미달성")';

-- 2. 출결캐싱 테이블
CREATE TABLE ATT_CACHE (
    ATT_CACHE_NO NUMBER NOT NULL,
    AVERAGE_COUNT NUMBER NULL,
    MIN_COUNT NUMBER NULL,
    MAX_COUNT NUMBER NULL,
    CONSTRAINT PK_ATT_CACHE PRIMARY KEY (ATT_CACHE_NO)
);

COMMENT ON COLUMN ATT_CACHE.ATT_CACHE_NO IS '출결 캐시 번호(PK)';
COMMENT ON COLUMN ATT_CACHE.AVERAGE_COUNT IS '평균 출석 인원';
COMMENT ON COLUMN ATT_CACHE.MIN_COUNT IS '최소 출석 인원';
COMMENT ON COLUMN ATT_CACHE.MAX_COUNT IS '최대 출석 인원';

-- 3. 재고_물품 테이블
CREATE TABLE STOCK (
    STOCK_ID NUMBER NOT NULL,
    STOCK_NAME VARCHAR2(200) NULL,
    STOCK_COUNT NUMBER NULL,
    STOCK_PRICE NUMBER NULL,
    STOCK_BRAND VARCHAR2(100) NULL,
    STOCK_CALL NUMBER NULL,
    CONSTRAINT PK_STOCK PRIMARY KEY (STOCK_ID)
);

COMMENT ON COLUMN STOCK.STOCK_ID IS '재고 물품 ID(PK)';
COMMENT ON COLUMN STOCK.STOCK_NAME IS '물품명';
COMMENT ON COLUMN STOCK.STOCK_COUNT IS '재고 수량';
COMMENT ON COLUMN STOCK.STOCK_PRICE IS '물품 가격';
COMMENT ON COLUMN STOCK.STOCK_BRAND IS '물품 브랜드';
COMMENT ON COLUMN STOCK.STOCK_CALL IS '공급업체 연락처';

-- ============================================
-- 2단계: GYM 테이블 (핵심 부모 테이블)
-- ============================================

-- 4. 헬스장센터 테이블
CREATE TABLE GYM (
    GYM_NO NUMBER NOT NULL,
    GYM_NAME VARCHAR2(200) NOT NULL,
    GYM_OWNER VARCHAR2(100) NOT NULL,
    GYM_PHONE NUMBER NOT NULL,
    GYM_ADDRESS VARCHAR2(500) NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    GYM_CREATEAT DATE DEFAULT SYSDATE NOT NULL,
    GYM_UPDATEAT DATE DEFAULT SYSDATE NOT NULL,
    GYM_PHOTO_PATH VARCHAR2(500) NULL,
    ATT_CACHE_NO NUMBER NOT NULL,
    CONSTRAINT PK_GYM PRIMARY KEY (GYM_NO),
    CONSTRAINT FK_GYM_ATT_CACHE FOREIGN KEY (ATT_CACHE_NO) REFERENCES ATT_CACHE(ATT_CACHE_NO),
    CONSTRAINT UQ_GYM_NAME UNIQUE (GYM_NAME),
    CONSTRAINT UQ_GYM_PHONE UNIQUE (GYM_PHONE)
);

COMMENT ON COLUMN GYM.GYM_NO IS '헬스장 번호(PK)';
COMMENT ON COLUMN GYM.GYM_NAME IS '헬스장명';
COMMENT ON COLUMN GYM.GYM_OWNER IS '대표자명';
COMMENT ON COLUMN GYM.GYM_PHONE IS '헬스장 전화번호';
COMMENT ON COLUMN GYM.GYM_ADDRESS IS '헬스장 주소';
COMMENT ON COLUMN GYM.STATUS IS '운영 상태(Y/N)';
COMMENT ON COLUMN GYM.GYM_CREATEAT IS '등록일';
COMMENT ON COLUMN GYM.GYM_UPDATEAT IS '수정일';
COMMENT ON COLUMN GYM.GYM_PHOTO_PATH IS '헬스장 사진 경로';
COMMENT ON COLUMN GYM.ATT_CACHE_NO IS '혼잡도 캐시 번호(FK)';

-- ============================================
-- 3단계: GYM 자식 테이블들
-- ============================================

-- 5. 헬스장 상세보기 테이블
CREATE TABLE GYM_DETAIL (
    GYM_DETAIL_NO NUMBER NOT NULL,
    INTRO VARCHAR2(500) NULL,
    FACILITIES_INFO VARCHAR2(1000) NULL,
    DETAIL_ADDRESS VARCHAR2(500) NULL,
    WEEK_BUSINESS_HOUR VARCHAR2(100) NULL,
    WEEKEND_BUSINESS_HOUR VARCHAR2(100) NULL,
    GYM_NO NUMBER NOT NULL,
    CONSTRAINT PK_GYM_DETAIL PRIMARY KEY (GYM_DETAIL_NO),
    CONSTRAINT FK_GYM_DETAIL_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO),
    CONSTRAINT UQ_GYM_DETAIL_GYM UNIQUE (GYM_NO)
);

COMMENT ON COLUMN GYM_DETAIL.GYM_DETAIL_NO IS '헬스장 상세정보 번호(PK)';
COMMENT ON COLUMN GYM_DETAIL.INTRO IS '헬스장 소개';  
COMMENT ON COLUMN GYM_DETAIL.FACILITIES_INFO IS '시설 정보(주차, 샤워실 등 고르는 정보들 ","로 구분)';
COMMENT ON COLUMN GYM_DETAIL.DETAIL_ADDRESS IS '상세 주소';
COMMENT ON COLUMN GYM_DETAIL.WEEK_BUSINESS_HOUR IS '평일 영업시간';
COMMENT ON COLUMN GYM_DETAIL.WEEKEND_BUSINESS_HOUR IS '주말 영업시간';
COMMENT ON COLUMN GYM_DETAIL.GYM_NO IS '헬스장 번호(FK)';

-- 6. 운동영상목록 테이블
CREATE TABLE YOUTUBE_URL (
    YOUTUBE_URL_NO NUMBER NOT NULL,
    YOUTUBE_URL_WRITER VARCHAR2(100) NULL,
    YOUTUBE_URL_TITLE VARCHAR2(500) NULL,
    YOUTUBE_URL VARCHAR2(500) NULL,
    GYM_NO NUMBER NOT NULL,
    CONSTRAINT PK_YOUTUBE_URL PRIMARY KEY (YOUTUBE_URL_NO),
    CONSTRAINT FK_YOUTUBE_URL_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN YOUTUBE_URL.YOUTUBE_URL_NO IS '영상 번호(PK)';
COMMENT ON COLUMN YOUTUBE_URL.YOUTUBE_URL_WRITER IS '영상 작성자';
COMMENT ON COLUMN YOUTUBE_URL.YOUTUBE_URL_TITLE IS '영상 제목';
COMMENT ON COLUMN YOUTUBE_URL.YOUTUBE_URL IS '유튜브 URL';
COMMENT ON COLUMN YOUTUBE_URL.GYM_NO IS '헬스장 번호(FK)';

-- 7. 헬스장공지사항 테이블
CREATE TABLE GYM_NOTICE (
    NOTICE_NO NUMBER NOT NULL,
    NOTICE_TITLE VARCHAR2(500) NULL,
    NOTICE_WRITER VARCHAR2(100) NULL,
    NOTICE_CATEGORY VARCHAR2(50) NULL,
    NOTICE_CONTENT VARCHAR2(4000) NULL,
    NOTICE_DATE DATE DEFAULT SYSDATE NULL,
    NOTICE_FIX_STATUS VARCHAR2(1) NULL, 
    NOTICE_FILE_PATH VARCHAR2(500) NULL,
    GYM_NO NUMBER NOT NULL,
    CONSTRAINT PK_GYM_NOTICE PRIMARY KEY (NOTICE_NO),
    CONSTRAINT FK_GYM_NOTICE_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN GYM_NOTICE.NOTICE_NO IS '공지사항 번호(PK)';
COMMENT ON COLUMN GYM_NOTICE.NOTICE_TITLE IS '공지사항 제목';
COMMENT ON COLUMN GYM_NOTICE.NOTICE_WRITER IS '작성자';
COMMENT ON COLUMN GYM_NOTICE.NOTICE_CATEGORY IS '공지사항 카테고리';
COMMENT ON COLUMN GYM_NOTICE.NOTICE_CONTENT IS '공지사항 내용';
COMMENT ON COLUMN GYM_NOTICE.NOTICE_DATE IS '작성일';
COMMENT ON COLUMN GYM_NOTICE.NOTICE_FIX_STATUS IS '고정 공지 여부(Y/N)';
COMMENT ON COLUMN GYM_NOTICE.NOTICE_FILE_PATH IS '첨부파일 경로';
COMMENT ON COLUMN GYM_NOTICE.GYM_NO IS '헬스장 번호(FK)';

-- 8. 머신 테이블
CREATE TABLE MACHINE (
    MACHINE_NO NUMBER NOT NULL,
    MACHINE_NAME VARCHAR2(200) NULL,
    BRAND VARCHAR2(100) NULL,
    MACHINE_PHOTO_PATH VARCHAR2(500) NULL,
    CONSTRAINT PK_MACHINE PRIMARY KEY (MACHINE_NO)
);

COMMENT ON COLUMN MACHINE.MACHINE_NO IS '기구 번호(PK)';
COMMENT ON COLUMN MACHINE.MACHINE_NAME IS '기구명';
COMMENT ON COLUMN MACHINE.BRAND IS '브랜드';
COMMENT ON COLUMN MACHINE.MACHINE_PHOTO_PATH IS '기구 사진 경로';

-- 9. 머신관리 테이블 (중계테이블: GYM + MACHINE)
CREATE TABLE MACHINE_MANAGE (
    MACHINE_MANAGE_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    MACHINE_NO NUMBER NOT NULL,
    MACHINE_CHECKED_DATE DATE NULL,
    MACHINE_NEXT_CHECK DATE NULL,
    MACHINE_STATUS VARCHAR2(20) DEFAULT '정상' NULL,
    CONSTRAINT PK_MACHINE_MANAGE PRIMARY KEY (MACHINE_MANAGE_NO),
    CONSTRAINT FK_MACHINE_MANAGE_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO),
    CONSTRAINT FK_MACHINE_MANAGE_MACHINE FOREIGN KEY (MACHINE_NO) REFERENCES MACHINE(MACHINE_NO),
    CONSTRAINT UQ_MACHINE_MANAGE UNIQUE (GYM_NO, MACHINE_NO)
);

COMMENT ON COLUMN MACHINE_MANAGE.MACHINE_MANAGE_NO IS '머신 관리 번호(PK)';
COMMENT ON COLUMN MACHINE_MANAGE.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN MACHINE_MANAGE.MACHINE_NO IS '기구 번호(FK)';
COMMENT ON COLUMN MACHINE_MANAGE.MACHINE_CHECKED_DATE IS '점검일';
COMMENT ON COLUMN MACHINE_MANAGE.MACHINE_NEXT_CHECK IS '다음 점검일(점검일+28 자동 계산)';
COMMENT ON COLUMN MACHINE_MANAGE.MACHINE_STATUS IS '기구 상태(정상/점검/고장)';

-- 10. 락커 테이블
CREATE TABLE LOCKER (
    LOCKER_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    LOCKER_REAL_NUM VARCHAR2(20) NOT NULL,
    LOCKER_STATUS VARCHAR2(20) DEFAULT NULL NULL,
    CONSTRAINT PK_LOCKER PRIMARY KEY (LOCKER_NO),
    CONSTRAINT FK_LOCKER_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO),
    CONSTRAINT UQ_LOCKER_REAL_NUM UNIQUE (GYM_NO, LOCKER_REAL_NUM)
);

COMMENT ON COLUMN LOCKER.LOCKER_NO IS '락커 번호(PK)';
COMMENT ON COLUMN LOCKER.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN LOCKER.LOCKER_REAL_NUM IS '실제 락커 번호';
COMMENT ON COLUMN LOCKER.LOCKER_STATUS IS '락커 상태(사용중/빈/만료/고장)';

-- 11. 재고관리 테이블 (중계테이블: GYM + STOCK)
CREATE TABLE STOCK_MANAGER (
    STOCK_MANAGE_NO NUMBER NOT NULL,
    STOCK_ID NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    STOCK_MANAGE_TYPE VARCHAR2(20) NULL,
    STOCK_MANAGE_DATE DATE DEFAULT SYSDATE NULL,
    STOCK_MANAGE_COUNT NUMBER NULL,
    CONSTRAINT PK_STOCK_MANAGER PRIMARY KEY (STOCK_MANAGE_NO),
    CONSTRAINT FK_STOCK_MANAGER_STOCK FOREIGN KEY (STOCK_ID) REFERENCES STOCK(STOCK_ID),
    CONSTRAINT FK_STOCK_MANAGER_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN STOCK_MANAGER.STOCK_MANAGE_NO IS '재고관리 번호(PK)';
COMMENT ON COLUMN STOCK_MANAGER.STOCK_ID IS '재고 물품 ID(FK)';
COMMENT ON COLUMN STOCK_MANAGER.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN STOCK_MANAGER.STOCK_MANAGE_TYPE IS '관리 유형(입고/출고)';  -- 트리거 필요
COMMENT ON COLUMN STOCK_MANAGER.STOCK_MANAGE_DATE IS '입출고일';
COMMENT ON COLUMN STOCK_MANAGER.STOCK_MANAGE_COUNT IS '입출고 수량';

-- 12. 상품 테이블
CREATE TABLE PRODUCT (
    PRODUCT_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    DURATION_MONTHS NUMBER NULL,
    PRODUCT_TYPE VARCHAR2(20) NULL,
    PRODUCT_START_DATE VARCHAR2(50) NULL,
    PRODUCT_PRICE NUMBER NULL,
    PRODUCT_STATUS VARCHAR2(1) DEFAULT 'Y' NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_NO),
    CONSTRAINT FK_PRODUCT_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN PRODUCT.PRODUCT_NO IS '상품 번호(PK)';
COMMENT ON COLUMN PRODUCT.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN PRODUCT.DURATION_MONTHS IS '이용 기간(1개월 단위: 30, 1년(12개월) 단위: 365)';
COMMENT ON COLUMN PRODUCT.PRODUCT_TYPE IS '상품 타입(회원권,락커,PT)';
COMMENT ON COLUMN PRODUCT.PRODUCT_START_DATE IS '판매 시작일';  
COMMENT ON COLUMN PRODUCT.PRODUCT_PRICE IS '상품 가격';
COMMENT ON COLUMN PRODUCT.PRODUCT_STATUS IS '판매 상태(Y/N)';

-- ============================================
-- 4단계: MEMBER 테이블
-- ============================================

-- 13. 회원 테이블
CREATE TABLE MEMBER (
    MEMBER_NO NUMBER NOT NULL,
    MEMBER_TYPE NUMBER NULL,
    MEMBER_ID VARCHAR2(50) NOT NULL,
    MEMBER_PWD VARCHAR2(100) NOT NULL,
    MEMBER_NAME VARCHAR2(100) NOT NULL,
    MEMBER_ADDRESS VARCHAR2(500) NULL,
    MEMBER_PHONE VARCHAR2(20) NOT NULL,
    MEMBER_BIRTH DATE NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    MEMBER_CREATEAT DATE DEFAULT SYSDATE NOT NULL,
    MEMBER_UPDATEAT DATE DEFAULT SYSDATE NOT NULL,
    MEMBER_EMAIL VARCHAR2(200) NULL,
    MEMBER_PHOTO_PATH VARCHAR2(500) NULL,
    GYM_NO NUMBER NULL,
    TRAINER_LICENSE VARCHAR2(200) NULL,
    TRAINER_CAREER VARCHAR2(1000) NULL,
    TRAINER_AWARD VARCHAR2(1000) NULL,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_NO),
    CONSTRAINT FK_MEMBER_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO),
    CONSTRAINT UQ_MEMBER_ID UNIQUE (MEMBER_ID),
    CONSTRAINT UQ_MEMBER_PHONE UNIQUE (MEMBER_PHONE),
    CONSTRAINT UQ_MEMBER_EMAIL UNIQUE (MEMBER_EMAIL)
);

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원 번호(PK)';
COMMENT ON COLUMN MEMBER.MEMBER_TYPE IS '회원 유형(1:일반/2:트레이너/3:헬스장운영자)';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원 이름';
COMMENT ON COLUMN MEMBER.MEMBER_ADDRESS IS '회원 주소';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE IS '회원 전화번호';
COMMENT ON COLUMN MEMBER.MEMBER_BIRTH IS '생년월일';
COMMENT ON COLUMN MEMBER.STATUS IS '회원 상태(Y:정상/N:탈퇴)';
COMMENT ON COLUMN MEMBER.MEMBER_CREATEAT IS '가입일';
COMMENT ON COLUMN MEMBER.MEMBER_UPDATEAT IS '정보 수정일';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS '회원 이메일';
COMMENT ON COLUMN MEMBER.MEMBER_PHOTO_PATH IS '프로필 사진 경로';
COMMENT ON COLUMN MEMBER.GYM_NO IS '소속 헬스장 번호(FK)';
COMMENT ON COLUMN MEMBER.TRAINER_LICENSE IS '트레이너 자격증';
COMMENT ON COLUMN MEMBER.TRAINER_CAREER IS '트레이너 경력';
COMMENT ON COLUMN MEMBER.TRAINER_AWARD IS '트레이너 수상경력';

-- ============================================
-- 5단계: MEMBER, GYM 자식 테이블들
-- ============================================

-- 14. 목표관리 테이블 (중계테이블: MEMBER + GOAL)
CREATE TABLE GOAL_MANAGE (
    GOAL_MANAGE_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    GOAL_NO NUMBER NOT NULL,
    GOAL_ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_GOAL_MANAGE PRIMARY KEY (GOAL_MANAGE_NO),
    CONSTRAINT FK_GOAL_MANAGE_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FK_GOAL_MANAGE_GOAL FOREIGN KEY (GOAL_NO) REFERENCES GOAL(GOAL_NO),
    CONSTRAINT UQ_GOAL_MANAGE UNIQUE (MEMBER_NO, GOAL_NO)
);

COMMENT ON TABLE GOAL_MANAGE IS '회원별 목표 관리 테이블';
COMMENT ON COLUMN GOAL_MANAGE.GOAL_MANAGE_NO IS '목표관리 번호(PK)';
COMMENT ON COLUMN GOAL_MANAGE.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN GOAL_MANAGE.GOAL_NO IS '목표 번호(FK)';
COMMENT ON COLUMN GOAL_MANAGE.GOAL_ENROLL_DATE IS '목표 등록일';

-- 15. 인바디기록 테이블
CREATE TABLE INBODY_RECORD (
    INBODY_NO NUMBER NOT NULL,
    INBODY_DATE DATE NULL,
    WEIGHT NUMBER NULL,
    SMM NUMBER NULL,
    PBF NUMBER NULL,
    BMI NUMBER NULL,
    MEMBER_NO NUMBER NOT NULL,
    CONSTRAINT PK_INBODY_RECORD PRIMARY KEY (INBODY_NO),
    CONSTRAINT FK_INBODY_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN INBODY_RECORD.INBODY_NO IS '인바디 기록 번호(PK)';
COMMENT ON COLUMN INBODY_RECORD.INBODY_DATE IS '측정일';
COMMENT ON COLUMN INBODY_RECORD.WEIGHT IS '체중';
COMMENT ON COLUMN INBODY_RECORD.SMM IS '골격근량';
COMMENT ON COLUMN INBODY_RECORD.PBF IS '체지방률';
COMMENT ON COLUMN INBODY_RECORD.BMI IS 'BMI';
COMMENT ON COLUMN INBODY_RECORD.MEMBER_NO IS '회원 번호(FK)';

-- 16. 방문예약 테이블 (중계테이블: GYM + MEMBER)
CREATE TABLE INQUIRY_RESERVE (
    INQUIRY_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    VISIT_DATETIME DATE NULL,
    REQUEST VARCHAR2(1000) NULL,
    INQUIRY_STATUS VARCHAR2(20) NULL,
    INQUIRY_MEMO VARCHAR2(1000) NULL,
    CONSTRAINT PK_INQUIRY_RESERVE PRIMARY KEY (INQUIRY_NO),
    CONSTRAINT FK_INQUIRY_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO),
    CONSTRAINT FK_INQUIRY_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN INQUIRY_RESERVE.INQUIRY_NO IS '방문 예약 번호(PK)';
COMMENT ON COLUMN INQUIRY_RESERVE.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN INQUIRY_RESERVE.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN INQUIRY_RESERVE.VISIT_DATETIME IS '방문 예정 일시';
COMMENT ON COLUMN INQUIRY_RESERVE.REQUEST IS '요청사항';
COMMENT ON COLUMN INQUIRY_RESERVE.INQUIRY_STATUS IS '예약 상태';
COMMENT ON COLUMN INQUIRY_RESERVE.INQUIRY_MEMO IS '메모';

-- 17. 출석 테이블 (중계테이블: GYM + MEMBER)
CREATE TABLE ATTENDANCE (
    ATTENDANCE_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    CHECK_IN_INFO VARCHAR2(20) NULL,
    ATTENDANCE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ATTENDANCE PRIMARY KEY (ATTENDANCE_NO),
    CONSTRAINT FK_ATTENDANCE_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO),
    CONSTRAINT FK_ATTENDANCE_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN ATTENDANCE.ATTENDANCE_NO IS '출석 번호(PK)';
COMMENT ON COLUMN ATTENDANCE.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN ATTENDANCE.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN ATTENDANCE.CHECK_IN_INFO IS '출입 정보(입실/퇴실)';
COMMENT ON COLUMN ATTENDANCE.ATTENDANCE_DATE IS '출석 일시';

-- 18. 구매 테이블 (중계테이블: GYM + MEMBER)
CREATE TABLE PURCHASE (
    PURCHASE_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    PURCHASE_DATE DATE DEFAULT SYSDATE NULL,
    PURCHASE_COST NUMBER NULL,
    PURCHASE_STATUS VARCHAR2(20) NULL,
    CONSTRAINT PK_PURCHASE PRIMARY KEY (PURCHASE_NO),
    CONSTRAINT FK_PURCHASE_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FK_PURCHASE_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN PURCHASE.PURCHASE_NO IS '구매 번호(PK)';
COMMENT ON COLUMN PURCHASE.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN PURCHASE.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN PURCHASE.PURCHASE_DATE IS '구매일';
COMMENT ON COLUMN PURCHASE.PURCHASE_COST IS '구매 금액';
COMMENT ON COLUMN PURCHASE.PURCHASE_STATUS IS '구매 상태(결제/취소/환불)';

-- ============================================
-- 6단계: PURCHASE 자식 테이블들
-- ============================================

-- 19. 구매아이템 테이블
CREATE TABLE PURCHASE_ITEM (
    PURCHASE_ITEM_NO NUMBER NOT NULL,
    MEMBERSHIP_PERIOD NUMBER NOT NULL,
    LOCKER_PERIOD NUMBER NULL,
    PT_COUNT NUMBER NULL,
    MEMBERSHIP_START_DATE DATE NULL,
    MEMBERSHIP_END_DATE DATE NULL,
    PURCHASE_NO NUMBER NOT NULL,
    CONSTRAINT PK_PURCHASE_ITEM PRIMARY KEY (PURCHASE_ITEM_NO),
    CONSTRAINT FK_PURCHASE_ITEM FOREIGN KEY (PURCHASE_NO) REFERENCES PURCHASE(PURCHASE_NO),
    CONSTRAINT UQ_PURCHASE_ITEM UNIQUE (PURCHASE_NO)
);

COMMENT ON COLUMN PURCHASE_ITEM.PURCHASE_ITEM_NO IS '구매항목 번호(PK)';
COMMENT ON COLUMN PURCHASE_ITEM.MEMBERSHIP_PERIOD IS '회원권 기간(일)';
COMMENT ON COLUMN PURCHASE_ITEM.LOCKER_PERIOD IS '락커 기간(일)';
COMMENT ON COLUMN PURCHASE_ITEM.PT_COUNT IS 'PT 횟수';
COMMENT ON COLUMN PURCHASE_ITEM.MEMBERSHIP_START_DATE IS '회원권 시작일';
COMMENT ON COLUMN PURCHASE_ITEM.MEMBERSHIP_END_DATE IS '회원권 종료일';
COMMENT ON COLUMN PURCHASE_ITEM.PURCHASE_NO IS '구매 번호(FK)';

-- 20. 회원권 테이블
CREATE TABLE MEMBERSHIP (
    MEMBERSHIP_NO NUMBER NOT NULL,
    PURCHASE_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    START_DATE DATE NULL,
    END_DATE DATE NULL,
    MEMBERSHIP_STATUS VARCHAR2(20) NULL,
    MEMBERSHIP_CREATEAT DATE DEFAULT SYSDATE NULL,
    MEMBERSHIP_UPDATE DATE DEFAULT SYSDATE NULL,
    CONSTRAINT PK_MEMBERSHIP PRIMARY KEY (MEMBERSHIP_NO),
    CONSTRAINT FK_MEMBERSHIP_PURCHASE FOREIGN KEY (PURCHASE_NO) REFERENCES PURCHASE(PURCHASE_NO),
    CONSTRAINT FK_MEMBERSHIP_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FK_MEMBERSHIP_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN MEMBERSHIP.MEMBERSHIP_NO IS '회원권 번호(PK)';
COMMENT ON COLUMN MEMBERSHIP.PURCHASE_NO IS '구매 번호(FK)';
COMMENT ON COLUMN MEMBERSHIP.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN MEMBERSHIP.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN MEMBERSHIP.START_DATE IS '시작일';
COMMENT ON COLUMN MEMBERSHIP.END_DATE IS '종료일';
COMMENT ON COLUMN MEMBERSHIP.MEMBERSHIP_STATUS IS '회원권 상태(정상/중단/환불/만료)';
COMMENT ON COLUMN MEMBERSHIP.MEMBERSHIP_CREATEAT IS '등록일';
COMMENT ON COLUMN MEMBERSHIP.MEMBERSHIP_UPDATE IS '수정일';

-- 21. PT이용권 테이블
CREATE TABLE PT_PASS (
    PT_PASS_NO NUMBER NOT NULL,
    PURCHASE_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    PT_START DATE NULL,
    PT_END DATE NULL,
    PT_USED_COUNT NUMBER DEFAULT 0 NULL,
    PT_TOTAL_COUNT NUMBER NULL,
    CONSTRAINT PK_PT_PASS PRIMARY KEY (PT_PASS_NO),
    CONSTRAINT FK_PT_PASS_PURCHASE FOREIGN KEY (PURCHASE_NO) REFERENCES PURCHASE(PURCHASE_NO),
    CONSTRAINT FK_PT_PASS_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FK_PT_PASS_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN PT_PASS.PT_PASS_NO IS 'PT이용권 번호(PK)';
COMMENT ON COLUMN PT_PASS.PURCHASE_NO IS '구매 번호(FK)';
COMMENT ON COLUMN PT_PASS.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN PT_PASS.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN PT_PASS.PT_START IS 'PT 시작일';
COMMENT ON COLUMN PT_PASS.PT_END IS 'PT 종료일';
COMMENT ON COLUMN PT_PASS.PT_USED_COUNT IS '사용 횟수';
COMMENT ON COLUMN PT_PASS.PT_TOTAL_COUNT IS '전체 횟수';

-- 22. 락커이용권 테이블 (중계테이블: PURCHASE + LOCKER + MEMBER)
CREATE TABLE LOCKER_PASS (
    LOCKER_PASS_NO NUMBER NOT NULL,
    PURCHASE_NO NUMBER NOT NULL,
    LOCKER_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    LOCKER_PASS_START DATE NULL,
    LOCKER_END DATE NULL,
    LOCKER_PASS_STATUS VARCHAR2(20) NULL,
    CONSTRAINT PK_LOCKER_PASS PRIMARY KEY (LOCKER_PASS_NO),
    CONSTRAINT FK_LOCKER_PASS_PURCHASE FOREIGN KEY (PURCHASE_NO) REFERENCES PURCHASE(PURCHASE_NO),
    CONSTRAINT FK_LOCKER_PASS_LOCKER FOREIGN KEY (LOCKER_NO) REFERENCES LOCKER(LOCKER_NO),
    CONSTRAINT FK_LOCKER_PASS_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT UQ_LOCKER_PASS UNIQUE (LOCKER_NO, MEMBER_NO)
);

COMMENT ON COLUMN LOCKER_PASS.LOCKER_PASS_NO IS '락커이용권 번호(PK)';
COMMENT ON COLUMN LOCKER_PASS.PURCHASE_NO IS '구매 번호(FK)';
COMMENT ON COLUMN LOCKER_PASS.LOCKER_NO IS '락커 번호(FK)';
COMMENT ON COLUMN LOCKER_PASS.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN LOCKER_PASS.LOCKER_PASS_START IS '락커 시작일';
COMMENT ON COLUMN LOCKER_PASS.LOCKER_END IS '락커 종료일';
COMMENT ON COLUMN LOCKER_PASS.LOCKER_PASS_STATUS IS '락커 상태';

-- ============================================
-- 7단계: PT_PASS 자식 테이블
-- ============================================

-- 23. PT예약 테이블 (중계테이블: PT_PASS + MEMBER(트레이너))
CREATE TABLE PT_RESERVE (
    PT_RESERVE_NO NUMBER NOT NULL,
    PT_PASS_NO NUMBER NOT NULL,
    PT_RESERVE_TIME DATE NULL,
    PT_HOPE_TRAINER VARCHAR2(100) NULL,
    TRAINER_MEMBER_NO NUMBER NOT NULL,
    CONSTRAINT PK_PT_RESERVE PRIMARY KEY (PT_RESERVE_NO),
    CONSTRAINT FK_PT_RESERVE_PASS FOREIGN KEY (PT_PASS_NO) REFERENCES PT_PASS(PT_PASS_NO),
    CONSTRAINT FK_PT_RESERVE_TRAINER FOREIGN KEY (TRAINER_MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN PT_RESERVE.PT_RESERVE_NO IS 'PT예약 번호(PK)';
COMMENT ON COLUMN PT_RESERVE.PT_PASS_NO IS 'PT이용권 번호(FK)';
COMMENT ON COLUMN PT_RESERVE.PT_RESERVE_TIME IS '예약 일시';
COMMENT ON COLUMN PT_RESERVE.PT_HOPE_TRAINER IS '희망 트레이너';
COMMENT ON COLUMN PT_RESERVE.TRAINER_MEMBER_NO IS '담당 트레이너 번호(FK)';

-- 24. 매출 테이블
CREATE TABLE SALES (
    SALES_NO NUMBER NOT NULL,
    PURCHASE_NO NUMBER NOT NULL,
    STOCK_ID NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    SALES_TYPE VARCHAR2(20) NULL,
    SALES_DATE DATE DEFAULT SYSDATE NULL,
    CONSTRAINT PK_SALES PRIMARY KEY (SALES_NO),
    CONSTRAINT FK_SALES_PURCHASE FOREIGN KEY (PURCHASE_NO) REFERENCES PURCHASE(PURCHASE_NO),
    CONSTRAINT FK_SALES_STOCK FOREIGN KEY (STOCK_ID) REFERENCES STOCK(STOCK_ID),
    CONSTRAINT FK_SALES_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN SALES.SALES_NO IS '매출 번호(PK)';
COMMENT ON COLUMN SALES.PURCHASE_NO IS '구매 번호(FK)';
COMMENT ON COLUMN SALES.STOCK_ID IS '재고 물품 ID(FK)';
COMMENT ON COLUMN SALES.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN SALES.SALES_TYPE IS '매출 타입(회원권/PT/락커/물품)';
COMMENT ON COLUMN SALES.SALES_DATE IS '매출일';



-- ============================================
-- 시퀀스 생성
-- ============================================

CREATE SEQUENCE SEQ_GOAL_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ATT_CACHE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STOCK_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GYM_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GYM_DETAIL_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_YOUTUBE_URL_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTICE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MACHINE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MACHINE_MANAGE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOCKER_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STOCK_MANAGE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCT_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MNO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GOAL_MANAGE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INBODY_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INQUIRY_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ATTENDANCE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PURCHASE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PURCHASE_ITEM_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MEMBERSHIP_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PT_PASS_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOCKER_PASS_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PT_RESERVE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SALES_NO START WITH 1 INCREMENT BY 1;