-- ============================================
-- DROP 테이블 (역순으로 삭제 - 자식 테이블부터)
-- ============================================
DROP TABLE PT_RESERVE CASCADE CONSTRAINTS;
DROP TABLE LOCKER_PASS CASCADE CONSTRAINTS;
DROP TABLE PT_PASS CASCADE CONSTRAINTS;
DROP TABLE MEMBERSHIP CASCADE CONSTRAINTS;
DROP TABLE PURCHASE_ITEM CASCADE CONSTRAINTS;
DROP TABLE SALES CASCADE CONSTRAINTS;  -- PURCHASE, STOCK, GYM 참조
DROP TABLE ATTENDANCE CASCADE CONSTRAINTS;
DROP TABLE INQUIRY_RESERVE CASCADE CONSTRAINTS;
DROP TABLE INBODY_RECORD CASCADE CONSTRAINTS;
DROP TABLE GOAL_MANAGE CASCADE CONSTRAINTS;
DROP TABLE STOCK_MANAGER CASCADE CONSTRAINTS;
DROP TABLE MACHINE_MANAGE CASCADE CONSTRAINTS;
DROP TABLE PURCHASE CASCADE CONSTRAINTS;
DROP TABLE LOCKER CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE GYM_NOTICE CASCADE CONSTRAINTS;
DROP TABLE YOUTUBE_URL CASCADE CONSTRAINTS;
DROP TABLE GYM_DETAIL CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE GYM CASCADE CONSTRAINTS;
DROP TABLE STOCK CASCADE CONSTRAINTS;
DROP TABLE MACHINE CASCADE CONSTRAINTS;
DROP TABLE ATT_CACHE CASCADE CONSTRAINTS;
DROP TABLE GOAL CASCADE CONSTRAINTS;
-- 시퀀스 삭제
DROP SEQUENCE SEQ_GOAL_NO;
DROP SEQUENCE SEQ_ATT_CACHE_DETAIL_NO;
DROP SEQUENCE SEQ_STOCK_ID;
DROP SEQUENCE SEQ_GYM_NO;
DROP SEQUENCE SEQ_GYM_DETAIL_NO;
DROP SEQUENCE SEQ_YOUTUBE_URL_NO;
DROP SEQUENCE SEQ_NOTICE_NO;
DROP SEQUENCE SEQ_MACHINE_NO;
DROP SEQUENCE SEQ_MACHINE_MANAGE_NO;
DROP SEQUENCE SEQ_LOCKER_NO;
DROP SEQUENCE SEQ_STOCK_MANAGE_NO;
DROP SEQUENCE SEQ_PRODUCT_NO;
DROP SEQUENCE SEQ_MNO;
DROP SEQUENCE SEQ_GOAL_MANAGE_NO;
DROP SEQUENCE SEQ_INBODY_NO;
DROP SEQUENCE SEQ_INQUIRY_NO;
DROP SEQUENCE SEQ_ATTENDANCE_NO;
DROP SEQUENCE SEQ_PURCHASE_NO;
DROP SEQUENCE SEQ_PURCHASE_ITEM_NO;
DROP SEQUENCE SEQ_MEMBERSHIP_NO;
DROP SEQUENCE SEQ_PT_PASS_NO;
DROP SEQUENCE SEQ_LOCKER_PASS_NO;
DROP SEQUENCE SEQ_PT_RESERVE_NO;
DROP SEQUENCE SEQ_SALES_NO;
-- ============================================
-- 1단계: 독립 테이블 (부모 테이블)
-- ============================================

-- 1. 운동목표 테이블
CREATE TABLE GOAL (
    GOAL_NO NUMBER NOT NULL,
    GOAL_TITLE VARCHAR2(200) NOT NULL,
    GOAL_STATUS VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_GOAL PRIMARY KEY (GOAL_NO)
);

COMMENT ON COLUMN GOAL.GOAL_NO IS '목표 번호(PK)';
COMMENT ON COLUMN GOAL.GOAL_TITLE IS '목표 제목';
COMMENT ON COLUMN GOAL.GOAL_STATUS IS '목표 상태("달성","미달성")';

-- 2. 출결캐싱 테이블 (시간대별 혼잡도 저장)
CREATE TABLE ATT_CACHE (
    CACHE_DETAIL_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    CACHE_DATE DATE NOT NULL,
    TIME_SLOT VARCHAR2(10) NOT NULL,
    MEMBER_COUNT NUMBER NOT NULL,
    CONSTRAINT PK_ATT_CACHE PRIMARY KEY (CACHE_DETAIL_NO),
    CONSTRAINT FK_ATT_CACHE_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN ATT_CACHE.CACHE_DETAIL_NO IS '출결 캐시 상세 번호(PK)';
COMMENT ON COLUMN ATT_CACHE.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN ATT_CACHE.CACHE_DATE IS '캐시 날짜';
COMMENT ON COLUMN ATT_CACHE.TIME_SLOT IS '시간대 구간(예: 06-08, 08-10, 10-12, ... 20-22, 22-24)';
COMMENT ON COLUMN ATT_CACHE.MEMBER_COUNT IS '해당 시간대 평균 인원수';

-- 3. 재고_물품 테이블
CREATE TABLE STOCK (
    STOCK_ID NUMBER NOT NULL,
    STOCK_NAME VARCHAR2(200) NULL,
    STOCK_COUNT NUMBER NULL,
    STOCK_PRICE NUMBER NULL,
    STOCK_BRAND VARCHAR2(100) NULL,
    STOCK_CALL NUMBER NULL,
    CONSTRAINT PK_STOCK PRIMARY KEY (STOCK_ID)
);

COMMENT ON COLUMN STOCK.STOCK_ID IS '재고 물품 ID(PK)';
COMMENT ON COLUMN STOCK.STOCK_NAME IS '물품명';
COMMENT ON COLUMN STOCK.STOCK_COUNT IS '재고 수량';
COMMENT ON COLUMN STOCK.STOCK_PRICE IS '물품 가격';
COMMENT ON COLUMN STOCK.STOCK_BRAND IS '물품 브랜드';
COMMENT ON COLUMN STOCK.STOCK_CALL IS '공급업체 연락처';

-- ============================================
-- 2단계: GYM 테이블 (핵심 부모 테이블)
-- ============================================

-- 4. 헬스장센터 테이블
CREATE TABLE GYM (
    GYM_NO NUMBER NOT NULL,
    GYM_NAME VARCHAR2(200) NOT NULL,
    GYM_OWNER VARCHAR2(100) NOT NULL,
    GYM_PHONE NUMBER NOT NULL,
    GYM_ADDRESS VARCHAR2(500) NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    GYM_CREATEAT DATE DEFAULT SYSDATE NOT NULL,
    GYM_UPDATEAT DATE DEFAULT SYSDATE NOT NULL,
    GYM_PHOTO_PATH VARCHAR2(500) NULL,
    CONSTRAINT PK_GYM PRIMARY KEY (GYM_NO),
    CONSTRAINT UQ_GYM_NAME UNIQUE (GYM_NAME),
    CONSTRAINT UQ_GYM_PHONE UNIQUE (GYM_PHONE)
);

COMMENT ON COLUMN GYM.GYM_NO IS '헬스장 번호(PK)';
COMMENT ON COLUMN GYM.GYM_NAME IS '헬스장명';
COMMENT ON COLUMN GYM.GYM_OWNER IS '대표자명';
COMMENT ON COLUMN GYM.GYM_PHONE IS '헬스장 전화번호';
COMMENT ON COLUMN GYM.GYM_ADDRESS IS '헬스장 주소';
COMMENT ON COLUMN GYM.STATUS IS '운영 상태(Y/N)';
COMMENT ON COLUMN GYM.GYM_CREATEAT IS '등록일';
COMMENT ON COLUMN GYM.GYM_UPDATEAT IS '수정일';
COMMENT ON COLUMN GYM.GYM_PHOTO_PATH IS '헬스장 사진 경로';

-- ============================================
-- 3단계: GYM 자식 테이블들
-- ============================================

-- 5. 헬스장 상세보기 테이블
CREATE TABLE GYM_DETAIL (
    GYM_DETAIL_NO NUMBER NOT NULL,
    INTRO VARCHAR2(500) NULL,
    FACILITIES_INFO VARCHAR2(1000) NULL,
    DETAIL_ADDRESS VARCHAR2(500) NULL,
    WEEK_BUSINESS_HOUR VARCHAR2(100) NULL,
    WEEKEND_BUSINESS_HOUR VARCHAR2(100) NULL,
    GYM_NO NUMBER NOT NULL,
    CONSTRAINT PK_GYM_DETAIL PRIMARY KEY (GYM_DETAIL_NO),
    CONSTRAINT FK_GYM_DETAIL_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO),
    CONSTRAINT UQ_GYM_DETAIL_GYM UNIQUE (GYM_NO)
);

COMMENT ON COLUMN GYM_DETAIL.GYM_DETAIL_NO IS '헬스장 상세정보 번호(PK)';
COMMENT ON COLUMN GYM_DETAIL.INTRO IS '헬스장 소개';  
COMMENT ON COLUMN GYM_DETAIL.FACILITIES_INFO IS '시설 정보(주차, 샤워실 등 고르는 정보들 ","로 구분)';
COMMENT ON COLUMN GYM_DETAIL.DETAIL_ADDRESS IS '상세 주소';
COMMENT ON COLUMN GYM_DETAIL.WEEK_BUSINESS_HOUR IS '평일 영업시간';
COMMENT ON COLUMN GYM_DETAIL.WEEKEND_BUSINESS_HOUR IS '주말 영업시간';
COMMENT ON COLUMN GYM_DETAIL.GYM_NO IS '헬스장 번호(FK)';

-- 6. 운동영상목록 테이블
CREATE TABLE YOUTUBE_URL (
    YOUTUBE_URL_NO NUMBER NOT NULL,
    YOUTUBE_URL_WRITER VARCHAR2(100) NULL,
    YOUTUBE_URL_TITLE VARCHAR2(500) NULL,
    YOUTUBE_URL VARCHAR2(500) NULL,
    GYM_NO NUMBER NOT NULL,
    CONSTRAINT PK_YOUTUBE_URL PRIMARY KEY (YOUTUBE_URL_NO),
    CONSTRAINT FK_YOUTUBE_URL_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN YOUTUBE_URL.YOUTUBE_URL_NO IS '영상 번호(PK)';
COMMENT ON COLUMN YOUTUBE_URL.YOUTUBE_URL_WRITER IS '영상 작성자';
COMMENT ON COLUMN YOUTUBE_URL.YOUTUBE_URL_TITLE IS '영상 제목';
COMMENT ON COLUMN YOUTUBE_URL.YOUTUBE_URL IS '유튜브 URL';
COMMENT ON COLUMN YOUTUBE_URL.GYM_NO IS '헬스장 번호(FK)';

-- 7. 헬스장공지사항 테이블
CREATE TABLE GYM_NOTICE (
    NOTICE_NO NUMBER NOT NULL,
    NOTICE_TITLE VARCHAR2(500) NULL,
    NOTICE_WRITER VARCHAR2(100) NULL,
    NOTICE_CATEGORY VARCHAR2(50) NULL,
    NOTICE_CONTENT VARCHAR2(4000) NULL,
    NOTICE_DATE DATE DEFAULT SYSDATE NULL,
    NOTICE_FIX_STATUS VARCHAR2(1) NULL, 
    NOTICE_FILE_PATH VARCHAR2(500) NULL,
    GYM_NO NUMBER NOT NULL,
    CONSTRAINT PK_GYM_NOTICE PRIMARY KEY (NOTICE_NO),
    CONSTRAINT FK_GYM_NOTICE_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN GYM_NOTICE.NOTICE_NO IS '공지사항 번호(PK)';
COMMENT ON COLUMN GYM_NOTICE.NOTICE_TITLE IS '공지사항 제목';
COMMENT ON COLUMN GYM_NOTICE.NOTICE_WRITER IS '작성자';
COMMENT ON COLUMN GYM_NOTICE.NOTICE_CATEGORY IS '공지사항 카테고리';
COMMENT ON COLUMN GYM_NOTICE.NOTICE_CONTENT IS '공지사항 내용';
COMMENT ON COLUMN GYM_NOTICE.NOTICE_DATE IS '작성일';
COMMENT ON COLUMN GYM_NOTICE.NOTICE_FIX_STATUS IS '고정 공지 여부(Y/N)';
COMMENT ON COLUMN GYM_NOTICE.NOTICE_FILE_PATH IS '첨부파일 경로';
COMMENT ON COLUMN GYM_NOTICE.GYM_NO IS '헬스장 번호(FK)';

-- 8. 머신 테이블
CREATE TABLE MACHINE (
    MACHINE_NO NUMBER NOT NULL,
    MACHINE_NAME VARCHAR2(200) NULL,
    BRAND VARCHAR2(100) NULL,
    MACHINE_PHOTO_PATH VARCHAR2(500) NULL,
    CONSTRAINT PK_MACHINE PRIMARY KEY (MACHINE_NO)
);

COMMENT ON COLUMN MACHINE.MACHINE_NO IS '기구 번호(PK)';
COMMENT ON COLUMN MACHINE.MACHINE_NAME IS '기구명';
COMMENT ON COLUMN MACHINE.BRAND IS '브랜드';
COMMENT ON COLUMN MACHINE.MACHINE_PHOTO_PATH IS '기구 사진 경로';

-- 9. 머신관리 테이블 (중계테이블: GYM + MACHINE)
CREATE TABLE MACHINE_MANAGE (
    MACHINE_MANAGE_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    MACHINE_NO NUMBER NOT NULL,
    MACHINE_CHECKED_DATE DATE NULL,
    MACHINE_NEXT_CHECK DATE NULL,
    MACHINE_STATUS VARCHAR2(20) DEFAULT '정상' NULL,
    CONSTRAINT PK_MACHINE_MANAGE PRIMARY KEY (MACHINE_MANAGE_NO),
    CONSTRAINT FK_MACHINE_MANAGE_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO),
    CONSTRAINT FK_MACHINE_MANAGE_MACHINE FOREIGN KEY (MACHINE_NO) REFERENCES MACHINE(MACHINE_NO),
    CONSTRAINT UQ_MACHINE_MANAGE UNIQUE (GYM_NO, MACHINE_NO)
);

COMMENT ON COLUMN MACHINE_MANAGE.MACHINE_MANAGE_NO IS '머신 관리 번호(PK)';
COMMENT ON COLUMN MACHINE_MANAGE.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN MACHINE_MANAGE.MACHINE_NO IS '기구 번호(FK)';
COMMENT ON COLUMN MACHINE_MANAGE.MACHINE_CHECKED_DATE IS '점검일';
COMMENT ON COLUMN MACHINE_MANAGE.MACHINE_NEXT_CHECK IS '다음 점검일(점검일+28 자동 계산)';
COMMENT ON COLUMN MACHINE_MANAGE.MACHINE_STATUS IS '기구 상태(정상/점검/고장)';

-- 10. 락커 테이블
CREATE TABLE LOCKER (
    LOCKER_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    LOCKER_REAL_NUM VARCHAR2(20) NOT NULL,
    LOCKER_STATUS VARCHAR2(20) DEFAULT NULL NULL,
    CONSTRAINT PK_LOCKER PRIMARY KEY (LOCKER_NO),
    CONSTRAINT FK_LOCKER_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO),
    CONSTRAINT UQ_LOCKER_REAL_NUM UNIQUE (GYM_NO, LOCKER_REAL_NUM)
);

COMMENT ON COLUMN LOCKER.LOCKER_NO IS '락커 번호(PK)';
COMMENT ON COLUMN LOCKER.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN LOCKER.LOCKER_REAL_NUM IS '실제 락커 번호';
COMMENT ON COLUMN LOCKER.LOCKER_STATUS IS '락커 상태(사용중/빈/만료/고장)';

-- 11. 재고관리 테이블 (중계테이블: GYM + STOCK)
CREATE TABLE STOCK_MANAGER (
    STOCK_MANAGE_NO NUMBER NOT NULL,
    STOCK_ID NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    STOCK_MANAGE_TYPE VARCHAR2(20) NULL,
    STOCK_MANAGE_DATE DATE DEFAULT SYSDATE NULL,
    STOCK_MANAGE_COUNT NUMBER NULL,
    CONSTRAINT PK_STOCK_MANAGER PRIMARY KEY (STOCK_MANAGE_NO),
    CONSTRAINT FK_STOCK_MANAGER_STOCK FOREIGN KEY (STOCK_ID) REFERENCES STOCK(STOCK_ID),
    CONSTRAINT FK_STOCK_MANAGER_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN STOCK_MANAGER.STOCK_MANAGE_NO IS '재고관리 번호(PK)';
COMMENT ON COLUMN STOCK_MANAGER.STOCK_ID IS '재고 물품 ID(FK)';
COMMENT ON COLUMN STOCK_MANAGER.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN STOCK_MANAGER.STOCK_MANAGE_TYPE IS '관리 유형(입고/출고)';  -- 트리거 필요
COMMENT ON COLUMN STOCK_MANAGER.STOCK_MANAGE_DATE IS '입출고일';
COMMENT ON COLUMN STOCK_MANAGER.STOCK_MANAGE_COUNT IS '입출고 수량';

-- 12. 상품 테이블
CREATE TABLE PRODUCT (
    PRODUCT_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    DURATION_MONTHS NUMBER NULL,
    PRODUCT_TYPE VARCHAR2(20) NULL,
    PRODUCT_START_DATE VARCHAR2(50) NULL,
    PRODUCT_PRICE NUMBER NULL,
    PRODUCT_STATUS VARCHAR2(1) DEFAULT 'Y' NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_NO),
    CONSTRAINT FK_PRODUCT_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN PRODUCT.PRODUCT_NO IS '상품 번호(PK)';
COMMENT ON COLUMN PRODUCT.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN PRODUCT.DURATION_MONTHS IS '이용 기간(1개월 단위: 30, 1년(12개월) 단위: 365)';
COMMENT ON COLUMN PRODUCT.PRODUCT_TYPE IS '상품 타입(회원권,락커,PT)';
COMMENT ON COLUMN PRODUCT.PRODUCT_START_DATE IS '판매 시작일';  
COMMENT ON COLUMN PRODUCT.PRODUCT_PRICE IS '상품 가격';
COMMENT ON COLUMN PRODUCT.PRODUCT_STATUS IS '판매 상태(Y/N)';

-- ============================================
-- 4단계: MEMBER 테이블
-- ============================================

-- 13. 회원 테이블
CREATE TABLE MEMBER (
    MEMBER_NO NUMBER NOT NULL,
    MEMBER_TYPE NUMBER NULL,
    MEMBER_ID VARCHAR2(50) NOT NULL,
    MEMBER_PWD VARCHAR2(100) NOT NULL,
    MEMBER_NAME VARCHAR2(100) NOT NULL,
    MEMBER_ADDRESS VARCHAR2(500) NULL,
    MEMBER_PHONE VARCHAR2(20) NOT NULL,
    MEMBER_BIRTH DATE NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    MEMBER_CREATEAT DATE DEFAULT SYSDATE NOT NULL,
    MEMBER_UPDATEAT DATE DEFAULT SYSDATE NOT NULL,
    MEMBER_EMAIL VARCHAR2(200) NULL,
    MEMBER_PHOTO_PATH VARCHAR2(500) NULL,
    GYM_NO NUMBER NULL,
    TRAINER_LICENSE VARCHAR2(200) NULL,
    TRAINER_CAREER VARCHAR2(1000) NULL,
    TRAINER_AWARD VARCHAR2(1000) NULL,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_NO),
    CONSTRAINT FK_MEMBER_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO),
    CONSTRAINT UQ_MEMBER_ID UNIQUE (MEMBER_ID),
    CONSTRAINT UQ_MEMBER_PHONE UNIQUE (MEMBER_PHONE),
    CONSTRAINT UQ_MEMBER_EMAIL UNIQUE (MEMBER_EMAIL)
);

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원 번호(PK)';
COMMENT ON COLUMN MEMBER.MEMBER_TYPE IS '회원 유형(1:일반/2:트레이너/3:헬스장운영자)';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원 이름';
COMMENT ON COLUMN MEMBER.MEMBER_ADDRESS IS '회원 주소';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE IS '회원 전화번호';
COMMENT ON COLUMN MEMBER.MEMBER_BIRTH IS '생년월일';
COMMENT ON COLUMN MEMBER.STATUS IS '회원 상태(Y:정상/N:탈퇴)';
COMMENT ON COLUMN MEMBER.MEMBER_CREATEAT IS '가입일';
COMMENT ON COLUMN MEMBER.MEMBER_UPDATEAT IS '정보 수정일';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS '회원 이메일';
COMMENT ON COLUMN MEMBER.MEMBER_PHOTO_PATH IS '프로필 사진 경로';
COMMENT ON COLUMN MEMBER.GYM_NO IS '소속 헬스장 번호(FK)';
COMMENT ON COLUMN MEMBER.TRAINER_LICENSE IS '트레이너 자격증';
COMMENT ON COLUMN MEMBER.TRAINER_CAREER IS '트레이너 경력';
COMMENT ON COLUMN MEMBER.TRAINER_AWARD IS '트레이너 수상경력';

-- ============================================
-- 5단계: MEMBER, GYM 자식 테이블들
-- ============================================

-- 14. 목표관리 테이블 (중계테이블: MEMBER + GOAL)
CREATE TABLE GOAL_MANAGE (
    GOAL_MANAGE_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    GOAL_NO NUMBER NOT NULL,
    GOAL_ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_GOAL_MANAGE PRIMARY KEY (GOAL_MANAGE_NO),
    CONSTRAINT FK_GOAL_MANAGE_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FK_GOAL_MANAGE_GOAL FOREIGN KEY (GOAL_NO) REFERENCES GOAL(GOAL_NO),
    CONSTRAINT UQ_GOAL_MANAGE UNIQUE (MEMBER_NO, GOAL_NO)
);

COMMENT ON TABLE GOAL_MANAGE IS '회원별 목표 관리 테이블';
COMMENT ON COLUMN GOAL_MANAGE.GOAL_MANAGE_NO IS '목표관리 번호(PK)';
COMMENT ON COLUMN GOAL_MANAGE.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN GOAL_MANAGE.GOAL_NO IS '목표 번호(FK)';
COMMENT ON COLUMN GOAL_MANAGE.GOAL_ENROLL_DATE IS '목표 등록일';

-- 15. 인바디기록 테이블
CREATE TABLE INBODY_RECORD (
    INBODY_NO NUMBER NOT NULL,
    INBODY_DATE DATE NULL,
    WEIGHT NUMBER NULL,
    SMM NUMBER NULL,
    PBF NUMBER NULL,
    BMI NUMBER NULL,
    MEMBER_NO NUMBER NOT NULL,
    CONSTRAINT PK_INBODY_RECORD PRIMARY KEY (INBODY_NO),
    CONSTRAINT FK_INBODY_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN INBODY_RECORD.INBODY_NO IS '인바디 기록 번호(PK)';
COMMENT ON COLUMN INBODY_RECORD.INBODY_DATE IS '측정일';
COMMENT ON COLUMN INBODY_RECORD.WEIGHT IS '체중';
COMMENT ON COLUMN INBODY_RECORD.SMM IS '골격근량';
COMMENT ON COLUMN INBODY_RECORD.PBF IS '체지방률';
COMMENT ON COLUMN INBODY_RECORD.BMI IS 'BMI';
COMMENT ON COLUMN INBODY_RECORD.MEMBER_NO IS '회원 번호(FK)';

-- 16. 방문예약 테이블 (중계테이블: GYM + MEMBER)
CREATE TABLE INQUIRY_RESERVE (
    INQUIRY_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    VISIT_DATETIME DATE NULL,
    REQUEST VARCHAR2(1000) NULL,
    INQUIRY_STATUS VARCHAR2(20) NULL,
    INQUIRY_MEMO VARCHAR2(1000) NULL,
    CONSTRAINT PK_INQUIRY_RESERVE PRIMARY KEY (INQUIRY_NO),
    CONSTRAINT FK_INQUIRY_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO),
    CONSTRAINT FK_INQUIRY_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN INQUIRY_RESERVE.INQUIRY_NO IS '방문 예약 번호(PK)';
COMMENT ON COLUMN INQUIRY_RESERVE.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN INQUIRY_RESERVE.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN INQUIRY_RESERVE.VISIT_DATETIME IS '방문 예정 일시';
COMMENT ON COLUMN INQUIRY_RESERVE.REQUEST IS '요청사항';
COMMENT ON COLUMN INQUIRY_RESERVE.INQUIRY_STATUS IS '예약 상태';
COMMENT ON COLUMN INQUIRY_RESERVE.INQUIRY_MEMO IS '메모';

-- 17. 출석 테이블 (중계테이블: GYM + MEMBER)
CREATE TABLE ATTENDANCE (
    ATTENDANCE_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    CHECK_IN_INFO VARCHAR2(20) NULL,
    ATTENDANCE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ATTENDANCE PRIMARY KEY (ATTENDANCE_NO),
    CONSTRAINT FK_ATTENDANCE_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO),
    CONSTRAINT FK_ATTENDANCE_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN ATTENDANCE.ATTENDANCE_NO IS '출석 번호(PK)';
COMMENT ON COLUMN ATTENDANCE.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN ATTENDANCE.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN ATTENDANCE.CHECK_IN_INFO IS '출입 정보(입실/퇴실)';
COMMENT ON COLUMN ATTENDANCE.ATTENDANCE_DATE IS '출석 일시';

-- 18. 구매 테이블 (중계테이블: GYM + MEMBER)
CREATE TABLE PURCHASE (
    PURCHASE_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    PURCHASE_DATE DATE DEFAULT SYSDATE NULL,
    PURCHASE_COST NUMBER NULL,
    PURCHASE_STATUS VARCHAR2(20) NULL,
    CONSTRAINT PK_PURCHASE PRIMARY KEY (PURCHASE_NO),
    CONSTRAINT FK_PURCHASE_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FK_PURCHASE_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN PURCHASE.PURCHASE_NO IS '구매 번호(PK)';
COMMENT ON COLUMN PURCHASE.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN PURCHASE.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN PURCHASE.PURCHASE_DATE IS '구매일';
COMMENT ON COLUMN PURCHASE.PURCHASE_COST IS '구매 금액';
COMMENT ON COLUMN PURCHASE.PURCHASE_STATUS IS '구매 상태(결제/취소/환불)';

-- ============================================
-- 6단계: PURCHASE 자식 테이블들
-- ============================================

-- 19. 구매아이템 테이블
CREATE TABLE PURCHASE_ITEM (
    PURCHASE_ITEM_NO NUMBER NOT NULL,
    MEMBERSHIP_PERIOD NUMBER NOT NULL,
    LOCKER_PERIOD NUMBER NULL,
    PT_COUNT NUMBER NULL,
    MEMBERSHIP_START_DATE DATE NULL,
    MEMBERSHIP_END_DATE DATE NULL,
    PURCHASE_NO NUMBER NOT NULL,
    CONSTRAINT PK_PURCHASE_ITEM PRIMARY KEY (PURCHASE_ITEM_NO),
    CONSTRAINT FK_PURCHASE_ITEM FOREIGN KEY (PURCHASE_NO) REFERENCES PURCHASE(PURCHASE_NO),
    CONSTRAINT UQ_PURCHASE_ITEM UNIQUE (PURCHASE_NO)
);

COMMENT ON COLUMN PURCHASE_ITEM.PURCHASE_ITEM_NO IS '구매항목 번호(PK)';
COMMENT ON COLUMN PURCHASE_ITEM.MEMBERSHIP_PERIOD IS '회원권 기간(일)';
COMMENT ON COLUMN PURCHASE_ITEM.LOCKER_PERIOD IS '락커 기간(일)';
COMMENT ON COLUMN PURCHASE_ITEM.PT_COUNT IS 'PT 횟수';
COMMENT ON COLUMN PURCHASE_ITEM.MEMBERSHIP_START_DATE IS '회원권 시작일';
COMMENT ON COLUMN PURCHASE_ITEM.MEMBERSHIP_END_DATE IS '회원권 종료일';
COMMENT ON COLUMN PURCHASE_ITEM.PURCHASE_NO IS '구매 번호(FK)';

-- 20. 회원권 테이블
CREATE TABLE MEMBERSHIP (
    MEMBERSHIP_NO NUMBER NOT NULL,
    PURCHASE_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    START_DATE DATE NULL,
    END_DATE DATE NULL,
    MEMBERSHIP_STATUS VARCHAR2(20) NULL,
    MEMBERSHIP_CREATEAT DATE DEFAULT SYSDATE NULL,
    MEMBERSHIP_UPDATE DATE DEFAULT SYSDATE NULL,
    CONSTRAINT PK_MEMBERSHIP PRIMARY KEY (MEMBERSHIP_NO),
    CONSTRAINT FK_MEMBERSHIP_PURCHASE FOREIGN KEY (PURCHASE_NO) REFERENCES PURCHASE(PURCHASE_NO),
    CONSTRAINT FK_MEMBERSHIP_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FK_MEMBERSHIP_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN MEMBERSHIP.MEMBERSHIP_NO IS '회원권 번호(PK)';
COMMENT ON COLUMN MEMBERSHIP.PURCHASE_NO IS '구매 번호(FK)';
COMMENT ON COLUMN MEMBERSHIP.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN MEMBERSHIP.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN MEMBERSHIP.START_DATE IS '시작일';
COMMENT ON COLUMN MEMBERSHIP.END_DATE IS '종료일';
COMMENT ON COLUMN MEMBERSHIP.MEMBERSHIP_STATUS IS '회원권 상태(정상/중단/환불/만료)';
COMMENT ON COLUMN MEMBERSHIP.MEMBERSHIP_CREATEAT IS '등록일';
COMMENT ON COLUMN MEMBERSHIP.MEMBERSHIP_UPDATE IS '수정일';

-- 21. PT이용권 테이블
CREATE TABLE PT_PASS (
    PT_PASS_NO NUMBER NOT NULL,
    PURCHASE_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    PT_START DATE NULL,
    PT_END DATE NULL,
    PT_USED_COUNT NUMBER DEFAULT 0 NULL,
    PT_TOTAL_COUNT NUMBER NULL,
    CONSTRAINT PK_PT_PASS PRIMARY KEY (PT_PASS_NO),
    CONSTRAINT FK_PT_PASS_PURCHASE FOREIGN KEY (PURCHASE_NO) REFERENCES PURCHASE(PURCHASE_NO),
    CONSTRAINT FK_PT_PASS_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FK_PT_PASS_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN PT_PASS.PT_PASS_NO IS 'PT이용권 번호(PK)';
COMMENT ON COLUMN PT_PASS.PURCHASE_NO IS '구매 번호(FK)';
COMMENT ON COLUMN PT_PASS.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN PT_PASS.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN PT_PASS.PT_START IS 'PT 시작일';
COMMENT ON COLUMN PT_PASS.PT_END IS 'PT 종료일';
COMMENT ON COLUMN PT_PASS.PT_USED_COUNT IS '사용 횟수';
COMMENT ON COLUMN PT_PASS.PT_TOTAL_COUNT IS '전체 횟수';

-- 22. 락커이용권 테이블 (중계테이블: PURCHASE + LOCKER + MEMBER)
CREATE TABLE LOCKER_PASS (
    LOCKER_PASS_NO NUMBER NOT NULL,
    PURCHASE_NO NUMBER NOT NULL,
    LOCKER_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    LOCKER_PASS_START DATE NULL,
    LOCKER_END DATE NULL,
    LOCKER_PASS_STATUS VARCHAR2(20) NULL,
    CONSTRAINT PK_LOCKER_PASS PRIMARY KEY (LOCKER_PASS_NO),
    CONSTRAINT FK_LOCKER_PASS_PURCHASE FOREIGN KEY (PURCHASE_NO) REFERENCES PURCHASE(PURCHASE_NO),
    CONSTRAINT FK_LOCKER_PASS_LOCKER FOREIGN KEY (LOCKER_NO) REFERENCES LOCKER(LOCKER_NO),
    CONSTRAINT FK_LOCKER_PASS_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT UQ_LOCKER_PASS UNIQUE (LOCKER_NO, MEMBER_NO)
);

COMMENT ON COLUMN LOCKER_PASS.LOCKER_PASS_NO IS '락커이용권 번호(PK)';
COMMENT ON COLUMN LOCKER_PASS.PURCHASE_NO IS '구매 번호(FK)';
COMMENT ON COLUMN LOCKER_PASS.LOCKER_NO IS '락커 번호(FK)';
COMMENT ON COLUMN LOCKER_PASS.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN LOCKER_PASS.LOCKER_PASS_START IS '락커 시작일';
COMMENT ON COLUMN LOCKER_PASS.LOCKER_END IS '락커 종료일';
COMMENT ON COLUMN LOCKER_PASS.LOCKER_PASS_STATUS IS '락커 상태';

-- ============================================
-- 7단계: PT_PASS 자식 테이블
-- ============================================

-- 23. PT예약 테이블 (중계테이블: PT_PASS + MEMBER(트레이너))
CREATE TABLE PT_RESERVE (
    PT_RESERVE_NO NUMBER NOT NULL,
    PT_PASS_NO NUMBER NOT NULL,
    PT_RESERVE_TIME DATE NULL,
    PT_HOPE_TRAINER VARCHAR2(100) NULL,
    TRAINER_MEMBER_NO NUMBER NOT NULL,
    CONSTRAINT PK_PT_RESERVE PRIMARY KEY (PT_RESERVE_NO),
    CONSTRAINT FK_PT_RESERVE_PASS FOREIGN KEY (PT_PASS_NO) REFERENCES PT_PASS(PT_PASS_NO),
    CONSTRAINT FK_PT_RESERVE_TRAINER FOREIGN KEY (TRAINER_MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN PT_RESERVE.PT_RESERVE_NO IS 'PT예약 번호(PK)';
COMMENT ON COLUMN PT_RESERVE.PT_PASS_NO IS 'PT이용권 번호(FK)';
COMMENT ON COLUMN PT_RESERVE.PT_RESERVE_TIME IS '예약 일시';
COMMENT ON COLUMN PT_RESERVE.PT_HOPE_TRAINER IS '희망 트레이너';
COMMENT ON COLUMN PT_RESERVE.TRAINER_MEMBER_NO IS '담당 트레이너 번호(FK)';

-- 24. 매출 테이블
CREATE TABLE SALES (
    SALES_NO NUMBER NOT NULL,
    PURCHASE_NO NUMBER NOT NULL,
    STOCK_ID NUMBER NOT NULL,
    GYM_NO NUMBER NOT NULL,
    SALES_TYPE VARCHAR2(20) NULL,
    SALES_DATE DATE DEFAULT SYSDATE NULL,
    CONSTRAINT PK_SALES PRIMARY KEY (SALES_NO),
    CONSTRAINT FK_SALES_PURCHASE FOREIGN KEY (PURCHASE_NO) REFERENCES PURCHASE(PURCHASE_NO),
    CONSTRAINT FK_SALES_STOCK FOREIGN KEY (STOCK_ID) REFERENCES STOCK(STOCK_ID),
    CONSTRAINT FK_SALES_GYM FOREIGN KEY (GYM_NO) REFERENCES GYM(GYM_NO)
);

COMMENT ON COLUMN SALES.SALES_NO IS '매출 번호(PK)';
COMMENT ON COLUMN SALES.PURCHASE_NO IS '구매 번호(FK)';
COMMENT ON COLUMN SALES.STOCK_ID IS '재고 물품 ID(FK)';
COMMENT ON COLUMN SALES.GYM_NO IS '헬스장 번호(FK)';
COMMENT ON COLUMN SALES.SALES_TYPE IS '매출 타입(회원권/PT/락커/물품)';
COMMENT ON COLUMN SALES.SALES_DATE IS '매출일';



-- ============================================
-- 시퀀스 생성
-- ============================================

CREATE SEQUENCE SEQ_GOAL_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ATT_CACHE_DETAIL_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STOCK_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GYM_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GYM_DETAIL_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_YOUTUBE_URL_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTICE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MACHINE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MACHINE_MANAGE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOCKER_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STOCK_MANAGE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCT_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MNO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GOAL_MANAGE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INBODY_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INQUIRY_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ATTENDANCE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PURCHASE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PURCHASE_ITEM_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MEMBERSHIP_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PT_PASS_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOCKER_PASS_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PT_RESERVE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SALES_NO START WITH 1 INCREMENT BY 1;

ALTER TABLE PT_RESERVE
    RENAME COLUMN PT_HOPE_TRAINER TO PT_TRAINER;
ALTER TABLE PT_RESERVE
    ADD PT_RESERVE_STATUS VARCHAR2(2);
COMMENT ON COLUMN PT_RESERVE.PT_TRAINER IS 'PT트레이너';


-- ============================================
-- GymHub 더미 데이터 INSERT (NOT NULL 제약조건 준수)
-- 부모-자식 관계를 고려한 순차적 데이터 삽입
-- ============================================

-- ============================================
-- 1단계: 독립 테이블 (부모 테이블)
-- ============================================

-- 1. GOAL (운동목표) - 모든 컬럼 NOT NULL
INSERT INTO GOAL VALUES (SEQ_GOAL_NO.NEXTVAL, '체중 감량 10kg', '미달성');
INSERT INTO GOAL VALUES (SEQ_GOAL_NO.NEXTVAL, '근육량 5kg 증가', '미달성');
INSERT INTO GOAL VALUES (SEQ_GOAL_NO.NEXTVAL, '체지방률 15% 이하', '달성');
INSERT INTO GOAL VALUES (SEQ_GOAL_NO.NEXTVAL, '벤치프레스 100kg', '미달성');
INSERT INTO GOAL VALUES (SEQ_GOAL_NO.NEXTVAL, '스쿼트 150kg', '미달성');
INSERT INTO GOAL VALUES (SEQ_GOAL_NO.NEXTVAL, '데드리프트 180kg', '달성');
INSERT INTO GOAL VALUES (SEQ_GOAL_NO.NEXTVAL, '하프마라톤 완주', '미달성');
INSERT INTO GOAL VALUES (SEQ_GOAL_NO.NEXTVAL, '체력 테스트 A등급', '달성');

-- 2. ATT_CACHE (출결캐싱) - 시간대별 혼잡도 데이터는 배치 작업으로 자동 생성되므로 더미 데이터 없음

-- 3. STOCK (재고_물품) - STOCK_ID만 NOT NULL
INSERT INTO STOCK VALUES (SEQ_STOCK_ID.NEXTVAL, '프로틴 파우더', 50, 45000, '마이프로틴', 025551234);
INSERT INTO STOCK VALUES (SEQ_STOCK_ID.NEXTVAL, 'BCAA', 30, 35000, '옵티멈뉴트리션', 025552345);
INSERT INTO STOCK VALUES (SEQ_STOCK_ID.NEXTVAL, '크레아틴', 40, 28000, '머슬팜', 025553456);
INSERT INTO STOCK VALUES (SEQ_STOCK_ID.NEXTVAL, '운동 장갑', 25, 15000, '나이키', 025554567);
INSERT INTO STOCK VALUES (SEQ_STOCK_ID.NEXTVAL, '요가매트', 20, 35000, '아디다스', 025555678);
INSERT INTO STOCK VALUES (SEQ_STOCK_ID.NEXTVAL, '물통 1L', 60, 12000, '언더아머', 025556789);
INSERT INTO STOCK VALUES (SEQ_STOCK_ID.NEXTVAL, '트레이닝 벨트', 15, 45000, '샤크', 025557890);
INSERT INTO STOCK VALUES (SEQ_STOCK_ID.NEXTVAL, '손목 보호대', 35, 18000, '리복', 025558901);

-- ============================================
-- 2단계: GYM 테이블
-- ============================================

-- 4. GYM (헬스장센터) - 대부분 NOT NULL
INSERT INTO GYM VALUES (SEQ_GYM_NO.NEXTVAL, '강남 피트니스', '김대표', 0212341234, '서울 강남구 테헤란로 123', 'Y', SYSDATE, SYSDATE, '/images/gym1.jpg');
INSERT INTO GYM VALUES (SEQ_GYM_NO.NEXTVAL, '홍대 헬스클럽', '이사장', 0223452345, '서울 마포구 홍익로 456', 'Y', SYSDATE, SYSDATE, '/images/gym2.jpg');
INSERT INTO GYM VALUES (SEQ_GYM_NO.NEXTVAL, '판교 스포츠센터', '박원장', 0334563456, '경기 성남시 분당구 판교로 789', 'Y', SYSDATE, SYSDATE, '/images/gym3.jpg');
INSERT INTO GYM VALUES (SEQ_GYM_NO.NEXTVAL, '잠실 휘트니스', '최관장', 0245674567, '서울 송파구 올림픽로 321', 'Y', SYSDATE, SYSDATE, '/images/gym4.jpg');
INSERT INTO GYM VALUES (SEQ_GYM_NO.NEXTVAL, '신촌 짐', '정대표', 0256785678, '서울 서대문구 신촌로 654', 'Y', SYSDATE, SYSDATE, '/images/gym5.jpg');
INSERT INTO GYM VALUES (SEQ_GYM_NO.NEXTVAL, '수원 스포츠클럽', '강사장', 0317896789, '경기 수원시 영통구 광교로 987', 'Y', SYSDATE, SYSDATE, '/images/gym6.jpg');
INSERT INTO GYM VALUES (SEQ_GYM_NO.NEXTVAL, '분당 헬스장', '조원장', 0318907890, '경기 성남시 분당구 정자로 147', 'Y', SYSDATE, SYSDATE, '/images/gym7.jpg');
INSERT INTO GYM VALUES (SEQ_GYM_NO.NEXTVAL, '일산 피트니스', '윤관장', 0319018901, '경기 고양시 일산동구 중앙로 258', 'Y', SYSDATE, SYSDATE, '/images/gym8.jpg');

-- ============================================
-- 3단계: GYM 자식 테이블들
-- ============================================

-- 5. GYM_DETAIL (헬스장 상세보기) - GYM_DETAIL_NO, GYM_NO만 NOT NULL
INSERT INTO GYM_DETAIL VALUES (SEQ_GYM_DETAIL_NO.NEXTVAL, '최신 시설과 전문 트레이너가 있는 프리미엄 헬스장', '주차장,샤워실,락커룸,사우나,GX프로그램,무료wifi,24시간', '서울 강남구 테헤란로 123, 3층', '00:00-24:00', '00:00-24:00', 1);
INSERT INTO GYM_DETAIL VALUES (SEQ_GYM_DETAIL_NO.NEXTVAL, '젊은 분위기의 감성 헬스클럽', '주차장,샤워실,락커룸,카페테리아', '서울 마포구 홍익로 456, 2층', '07:00-22:00', '09:00-19:00', 2);
INSERT INTO GYM_DETAIL VALUES (SEQ_GYM_DETAIL_NO.NEXTVAL, '판교 최대 규모 종합 스포츠센터', '주차장,샤워실,락커룸,사우나,수영장,GX프로그램', '경기 성남시 분당구 판교로 789, 지하1층-2층', '05:00-24:00', '07:00-22:00', 3);
INSERT INTO GYM_DETAIL VALUES (SEQ_GYM_DETAIL_NO.NEXTVAL, '올림픽공원 인근 프리미엄 피트니스', '주차장,샤워실,락커룸,사우나,GX프로그램,PT', '서울 송파구 올림픽로 321, 4층', '06:00-23:00', '08:00-21:00', 4);
INSERT INTO GYM_DETAIL VALUES (SEQ_GYM_DETAIL_NO.NEXTVAL, '대학가 저렴한 헬스장', '샤워실,락커룸,24시간', '서울 서대문구 신촌로 654, 지하1층', '00:00-24:00', '00:00-24:00', 5);
INSERT INTO GYM_DETAIL VALUES (SEQ_GYM_DETAIL_NO.NEXTVAL, '수원 광교 신도시 스포츠클럽', '주차장,샤워실,락커룸,사우나,GX프로그램,필라테스', '경기 수원시 영통구 광교로 987, 1-2층', '00:00-23:00', '00:00-24:00', 6);
INSERT INTO GYM_DETAIL VALUES (SEQ_GYM_DETAIL_NO.NEXTVAL, '분당 정자동 커뮤니티 헬스장', '주차장,샤워실,락커룸,무료wifi,GX프로그램', '경기 성남시 분당구 정자로 147, 3층', '07:00-22:00', '09:00-19:00', 7);
INSERT INTO GYM_DETAIL VALUES (SEQ_GYM_DETAIL_NO.NEXTVAL, '일산 중심가 프리미엄 피트니스', '주차장,샤워실,락커룸,사우나,카페', '경기 고양시 일산동구 중앙로 258, 5층', '06:00-23:00', '08:00-21:00', 8);

-- 6. YOUTUBE_URL (운동영상목록) - YOUTUBE_URL_NO, GYM_NO만 NOT NULL
INSERT INTO YOUTUBE_URL VALUES (SEQ_YOUTUBE_URL_NO.NEXTVAL, '박트레이너', '초보자를 위한 하체 운동', 'https://youtube.com/watch?v=abc123', 1);
INSERT INTO YOUTUBE_URL VALUES (SEQ_YOUTUBE_URL_NO.NEXTVAL, '김코치', '가슴 근육 키우기 루틴', 'https://youtube.com/watch?v=def456', 1);
INSERT INTO YOUTUBE_URL VALUES (SEQ_YOUTUBE_URL_NO.NEXTVAL, '이강사', '등 운동 완벽 가이드', 'https://youtube.com/watch?v=ghi789', 2);
INSERT INTO YOUTUBE_URL VALUES (SEQ_YOUTUBE_URL_NO.NEXTVAL, '최트레이너', '어깨 운동 5가지', 'https://youtube.com/watch?v=jkl012', 2);
INSERT INTO YOUTUBE_URL VALUES (SEQ_YOUTUBE_URL_NO.NEXTVAL, '정코치', '복근 만들기 홈트', 'https://youtube.com/watch?v=mno345', 3);
INSERT INTO YOUTUBE_URL VALUES (SEQ_YOUTUBE_URL_NO.NEXTVAL, '강강사', '팔 운동 집중 공략', 'https://youtube.com/watch?v=pqr678', 3);
INSERT INTO YOUTUBE_URL VALUES (SEQ_YOUTUBE_URL_NO.NEXTVAL, '조트레이너', '전신 순환 운동', 'https://youtube.com/watch?v=stu901', 4);
INSERT INTO YOUTUBE_URL VALUES (SEQ_YOUTUBE_URL_NO.NEXTVAL, '윤코치', '스트레칭 루틴', 'https://youtube.com/watch?v=vwx234', 4);

-- 7. GYM_NOTICE (헬스장공지사항) - NOTICE_NO, GYM_NO만 NOT NULL
INSERT INTO GYM_NOTICE VALUES (SEQ_NOTICE_NO.NEXTVAL, '연말연시 운영시간 안내', '관리자', '긴급', '12월 31일과 1월 1일은 오전 10시부터 오후 6시까지 운영합니다. 회원 여러분의 양해 부탁드립니다.', SYSDATE-5, 'Y', NULL, 1);
INSERT INTO GYM_NOTICE VALUES (SEQ_NOTICE_NO.NEXTVAL, '11월 신규 GX 프로그램 오픈', '박트레이너', '이벤트', '새로운 GX 프로그램이 준비되었습니다! 필라테스, 요가, 에어로빅 등 다양한 프로그램을 만나보세요.', SYSDATE-3, 'Y', '/notice/event1.jpg', 1);
INSERT INTO GYM_NOTICE VALUES (SEQ_NOTICE_NO.NEXTVAL, '시설 점검 안내', '시설관리팀', '중요', '내일(금)의 오전 2시부터 6시까지 시설 점검이 예정되어 있습니다. 해당 시간에는 이용이 불가합니다.', SYSDATE-2, 'N', NULL, 2);
INSERT INTO GYM_NOTICE VALUES (SEQ_NOTICE_NO.NEXTVAL, '신규 운동 기구 입고 완료', '이강사', '일반', '회원 여러분이 요청하신 최신 스미스머신과 케이블 크로스오버가 입고되었습니다. 2층 프리웨이트존에서 이용하실 수 있습니다.', SYSDATE-1, 'N', '/notice/machine1.jpg', 2);
INSERT INTO GYM_NOTICE VALUES (SEQ_NOTICE_NO.NEXTVAL, '여름 이벤트 안내', '관리자', '이벤트', '6-8월 신규 회원 등록시 PT 2회 무료 제공!', SYSDATE, 'N', NULL, 3);
INSERT INTO GYM_NOTICE VALUES (SEQ_NOTICE_NO.NEXTVAL, '락커룸 청소 시간 변경', '관리팀', '일반', '매주 목요일 락커룸 청소 시간이 오전 10시로 변경되었습니다.', SYSDATE, 'N', NULL, 3);
INSERT INTO GYM_NOTICE VALUES (SEQ_NOTICE_NO.NEXTVAL, '주차장 이용 안내', '시설관리', '중요', '주차장 만차시 인근 공영주차장을 이용해주세요. 주차권은 데스크에서 받으실 수 있습니다.', SYSDATE, 'Y', NULL, 4);
INSERT INTO GYM_NOTICE VALUES (SEQ_NOTICE_NO.NEXTVAL, 'PT 신규 트레이너 소개', '최트레이너', '일반', '새롭게 합류하신 박트레이너님을 소개합니다. 보디빌딩 대회 입상 경력이 있으십니다.', SYSDATE, 'N', '/notice/trainer1.jpg', 4);

-- 8. MACHINE (머신) - MACHINE_NO만 NOT NULL
INSERT INTO MACHINE VALUES (SEQ_MACHINE_NO.NEXTVAL, '트레드밀', 'Life Fitness', '/images/treadmill.jpg');
INSERT INTO MACHINE VALUES (SEQ_MACHINE_NO.NEXTVAL, '사이클', 'Technogym', '/images/cycle.jpg');
INSERT INTO MACHINE VALUES (SEQ_MACHINE_NO.NEXTVAL, '스미스머신', 'Hammer Strength', '/images/smith.jpg');
INSERT INTO MACHINE VALUES (SEQ_MACHINE_NO.NEXTVAL, '렉풀다운', 'Life Fitness', '/images/latpull.jpg');
INSERT INTO MACHINE VALUES (SEQ_MACHINE_NO.NEXTVAL, '레그프레스', 'Precor', '/images/legpress.jpg');
INSERT INTO MACHINE VALUES (SEQ_MACHINE_NO.NEXTVAL, '체스트프레스', 'Technogym', '/images/chestpress.jpg');
INSERT INTO MACHINE VALUES (SEQ_MACHINE_NO.NEXTVAL, '케이블 크로스오버', 'Life Fitness', '/images/cable.jpg');
INSERT INTO MACHINE VALUES (SEQ_MACHINE_NO.NEXTVAL, '로잉머신', 'Concept2', '/images/rowing.jpg');

-- 9. MACHINE_MANAGE (머신관리) - 모든 필드 NOT NULL
INSERT INTO MACHINE_MANAGE VALUES (SEQ_MACHINE_MANAGE_NO.NEXTVAL, 1, 1, SYSDATE-10, SYSDATE+18, '정상');
INSERT INTO MACHINE_MANAGE VALUES (SEQ_MACHINE_MANAGE_NO.NEXTVAL, 1, 2, SYSDATE-5, SYSDATE+23, '정상');
INSERT INTO MACHINE_MANAGE VALUES (SEQ_MACHINE_MANAGE_NO.NEXTVAL, 2, 3, SYSDATE-15, SYSDATE+13, '점검');
INSERT INTO MACHINE_MANAGE VALUES (SEQ_MACHINE_MANAGE_NO.NEXTVAL, 2, 4, SYSDATE-8, SYSDATE+20, '정상');
INSERT INTO MACHINE_MANAGE VALUES (SEQ_MACHINE_MANAGE_NO.NEXTVAL, 3, 5, SYSDATE-20, SYSDATE+8, '정상');
INSERT INTO MACHINE_MANAGE VALUES (SEQ_MACHINE_MANAGE_NO.NEXTVAL, 3, 6, SYSDATE-3, SYSDATE+25, '정상');
INSERT INTO MACHINE_MANAGE VALUES (SEQ_MACHINE_MANAGE_NO.NEXTVAL, 4, 7, SYSDATE-12, SYSDATE+16, '고장');
INSERT INTO MACHINE_MANAGE VALUES (SEQ_MACHINE_MANAGE_NO.NEXTVAL, 4, 8, SYSDATE-7, SYSDATE+21, '정상');

-- 10. LOCKER (락커) - 모든 필드 NOT NULL
INSERT INTO LOCKER VALUES (SEQ_LOCKER_NO.NEXTVAL, 1, '101', '빈');
INSERT INTO LOCKER VALUES (SEQ_LOCKER_NO.NEXTVAL, 1, '102', '사용중');
INSERT INTO LOCKER VALUES (SEQ_LOCKER_NO.NEXTVAL, 1, '103', '빈');
INSERT INTO LOCKER VALUES (SEQ_LOCKER_NO.NEXTVAL, 2, '201', '사용중');
INSERT INTO LOCKER VALUES (SEQ_LOCKER_NO.NEXTVAL, 2, '202', '빈');
INSERT INTO LOCKER VALUES (SEQ_LOCKER_NO.NEXTVAL, 3, '301', '만료');
INSERT INTO LOCKER VALUES (SEQ_LOCKER_NO.NEXTVAL, 3, '302', '빈');
INSERT INTO LOCKER VALUES (SEQ_LOCKER_NO.NEXTVAL, 4, '401', '사용중');

-- 11. STOCK_MANAGER (재고관리) - STOCK_MANAGE_NO, STOCK_ID, GYM_NO만 NOT NULL
INSERT INTO STOCK_MANAGER VALUES (SEQ_STOCK_MANAGE_NO.NEXTVAL, 1, 1, '입고', SYSDATE-30, 100);
INSERT INTO STOCK_MANAGER VALUES (SEQ_STOCK_MANAGE_NO.NEXTVAL, 1, 1, '출고', SYSDATE-25, 50);
INSERT INTO STOCK_MANAGER VALUES (SEQ_STOCK_MANAGE_NO.NEXTVAL, 2, 1, '입고', SYSDATE-20, 50);
INSERT INTO STOCK_MANAGER VALUES (SEQ_STOCK_MANAGE_NO.NEXTVAL, 2, 2, '출고', SYSDATE-15, 20);
INSERT INTO STOCK_MANAGER VALUES (SEQ_STOCK_MANAGE_NO.NEXTVAL, 3, 2, '입고', SYSDATE-10, 60);
INSERT INTO STOCK_MANAGER VALUES (SEQ_STOCK_MANAGE_NO.NEXTVAL, 4, 3, '출고', SYSDATE-5, 15);
INSERT INTO STOCK_MANAGER VALUES (SEQ_STOCK_MANAGE_NO.NEXTVAL, 5, 3, '입고', SYSDATE-3, 40);
INSERT INTO STOCK_MANAGER VALUES (SEQ_STOCK_MANAGE_NO.NEXTVAL, 6, 4, '출고', SYSDATE-1, 10);

-- 12. PRODUCT (상품) - PRODUCT_NO, GYM_NO만 NOT NULL
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT_NO.NEXTVAL, 1, 30, '회원권', '2025-01-01', 100000, 'Y');
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT_NO.NEXTVAL, 1, 90, '회원권', '2025-01-01', 270000, 'Y');
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT_NO.NEXTVAL, 1, 365, '회원권', '2025-01-01', 1000000, 'Y');
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT_NO.NEXTVAL, 2, 30, '락커', '2025-01-01', 30000, 'Y');
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT_NO.NEXTVAL, 2, 10, 'PT', '2025-01-01', 500000, 'Y');
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT_NO.NEXTVAL, 3, 20, 'PT', '2025-01-01', 900000, 'Y');
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT_NO.NEXTVAL, 3, 30, '회원권', '2025-01-01', 110000, 'Y');
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT_NO.NEXTVAL, 4, 90, '회원권', '2025-01-01', 280000, 'Y');

-- ============================================
-- 4단계: MEMBER 테이블
-- ============================================

-- 13. MEMBER (회원) - 대부분 NOT NULL
-- 일반 회원 (MEMBER_TYPE = 1)
INSERT INTO MEMBER VALUES (SEQ_MNO.NEXTVAL, 1, 'user01', 'pass1234!', '홍길동', '서울 강남구 테헤란로 100', '01012345678', TO_DATE('1990-05-15', 'YYYY-MM-DD'), 'Y', SYSDATE-100, SYSDATE, 'hong@email.com', '/profile/hong.jpg', 1, NULL, NULL, NULL);
INSERT INTO MEMBER VALUES (SEQ_MNO.NEXTVAL, 1, 'user02', 'pass1234!', '김영희', '서울 강남구 역삼로 200', '01023456789', TO_DATE('1995-08-22', 'YYYY-MM-DD'), 'Y', SYSDATE-90, SYSDATE, 'kim@email.com', '/profile/kim.jpg', 1, NULL, NULL, NULL);
INSERT INTO MEMBER VALUES (SEQ_MNO.NEXTVAL, 1, 'user03', 'pass1234!', '박철수', '서울 마포구 홍익로 300', '01034567890', TO_DATE('1988-03-10', 'YYYY-MM-DD'), 'Y', SYSDATE-80, SYSDATE, 'park@email.com', '/profile/park.jpg', 2, NULL, NULL, NULL);
INSERT INTO MEMBER VALUES (SEQ_MNO.NEXTVAL, 1, 'user04', 'pass1234!', '정수진', '경기 성남시 판교로 400', '01045678901', TO_DATE('1992-11-30', 'YYYY-MM-DD'), 'Y', SYSDATE-70, SYSDATE, 'jung@email.com', '/profile/jung.jpg', 3, NULL, NULL, NULL);

-- 트레이너 (MEMBER_TYPE = 2)
INSERT INTO MEMBER VALUES (SEQ_MNO.NEXTVAL, 2, 'trainer01', 'pass1234!', '이코치', '서울 강남구 선릉로 500', '01056789012', TO_DATE('1985-01-20', 'YYYY-MM-DD'), 'Y', SYSDATE-60, SYSDATE, 'lee@email.com', '/profile/lee.jpg', 1, '생활체육지도사 2급', '피트니스 트레이너 5년', '2023 보디빌딩 대회 입상');
INSERT INTO MEMBER VALUES (SEQ_MNO.NEXTVAL, 2, 'trainer02', 'pass1234!', '최트레이너', '서울 송파구 올림픽로 600', '01067890123', TO_DATE('1987-07-15', 'YYYY-MM-DD'), 'Y', SYSDATE-50, SYSDATE, 'choi@email.com', '/profile/choi.jpg', 2, 'NSCA-CPT', '퍼스널 트레이닝 7년', '2022 크로스핏 대회 3위');

-- 헬스장 운영자 (MEMBER_TYPE = 3)
INSERT INTO MEMBER VALUES (SEQ_MNO.NEXTVAL, 3, 'admin01', 'pass1234!', '김관장', '서울 강남구 테헤란로 123', '01078901234', TO_DATE('1980-12-05', 'YYYY-MM-DD'), 'Y', SYSDATE-40, SYSDATE, 'admin1@email.com', '/profile/admin1.jpg', 1, NULL, NULL, NULL);
INSERT INTO MEMBER VALUES (SEQ_MNO.NEXTVAL, 3, 'admin02', 'pass1234!', '박사장', '서울 마포구 홍익로 456', '01089012345', TO_DATE('1978-09-18', 'YYYY-MM-DD'), 'Y', SYSDATE-30, SYSDATE, 'admin2@email.com', '/profile/admin2.jpg', 2, NULL, NULL, NULL);

-- ============================================
-- 5단계: MEMBER, GYM 자식 테이블들
-- ============================================

-- 14. GOAL_MANAGE (목표관리) - 모든 필드 NOT NULL
INSERT INTO GOAL_MANAGE VALUES (SEQ_GOAL_MANAGE_NO.NEXTVAL, 1, 1, SYSDATE-30);
INSERT INTO GOAL_MANAGE VALUES (SEQ_GOAL_MANAGE_NO.NEXTVAL, 1, 2, SYSDATE-30);
INSERT INTO GOAL_MANAGE VALUES (SEQ_GOAL_MANAGE_NO.NEXTVAL, 2, 3, SYSDATE-25);
INSERT INTO GOAL_MANAGE VALUES (SEQ_GOAL_MANAGE_NO.NEXTVAL, 2, 4, SYSDATE-25);
INSERT INTO GOAL_MANAGE VALUES (SEQ_GOAL_MANAGE_NO.NEXTVAL, 3, 5, SYSDATE-20);
INSERT INTO GOAL_MANAGE VALUES (SEQ_GOAL_MANAGE_NO.NEXTVAL, 3, 6, SYSDATE-20);
INSERT INTO GOAL_MANAGE VALUES (SEQ_GOAL_MANAGE_NO.NEXTVAL, 4, 7, SYSDATE-15);
INSERT INTO GOAL_MANAGE VALUES (SEQ_GOAL_MANAGE_NO.NEXTVAL, 4, 8, SYSDATE-15);

-- 15. INBODY_RECORD (인바디기록) - INBODY_NO, MEMBER_NO만 NOT NULL
INSERT INTO INBODY_RECORD VALUES (SEQ_INBODY_NO.NEXTVAL, SYSDATE-60, 75.5, 32.5, 18.5, 24.2, 1);
INSERT INTO INBODY_RECORD VALUES (SEQ_INBODY_NO.NEXTVAL, SYSDATE-30, 73.2, 33.1, 17.2, 23.5, 1);
INSERT INTO INBODY_RECORD VALUES (SEQ_INBODY_NO.NEXTVAL, SYSDATE-50, 58.3, 21.5, 24.8, 21.3, 2);
INSERT INTO INBODY_RECORD VALUES (SEQ_INBODY_NO.NEXTVAL, SYSDATE-20, 57.1, 22.0, 23.5, 20.9, 2);
INSERT INTO INBODY_RECORD VALUES (SEQ_INBODY_NO.NEXTVAL, SYSDATE-45, 82.0, 38.5, 20.3, 26.1, 3);
INSERT INTO INBODY_RECORD VALUES (SEQ_INBODY_NO.NEXTVAL, SYSDATE-15, 79.5, 39.8, 18.5, 25.3, 3);
INSERT INTO INBODY_RECORD VALUES (SEQ_INBODY_NO.NEXTVAL, SYSDATE-40, 65.0, 24.5, 22.0, 22.8, 4);
INSERT INTO INBODY_RECORD VALUES (SEQ_INBODY_NO.NEXTVAL, SYSDATE-10, 63.5, 25.2, 20.5, 22.3, 4);

-- 16. INQUIRY_RESERVE (방문예약) - INQUIRY_NO, GYM_NO, MEMBER_NO만 NOT NULL
INSERT INTO INQUIRY_RESERVE VALUES (SEQ_INQUIRY_NO.NEXTVAL, 1, 1, SYSDATE+5, '운동 루틴 상담 원합니다', '예약완료', '오후 2시 방문 예정');
INSERT INTO INQUIRY_RESERVE VALUES (SEQ_INQUIRY_NO.NEXTVAL, 1, 2, SYSDATE+7, 'PT 상담 요청', '예약완료', '트레이너 배정 필요');
INSERT INTO INQUIRY_RESERVE VALUES (SEQ_INQUIRY_NO.NEXTVAL, 2, 3, SYSDATE+3, '시설 둘러보기', '대기중', NULL);
INSERT INTO INQUIRY_RESERVE VALUES (SEQ_INQUIRY_NO.NEXTVAL, 2, 4, SYSDATE+10, '회원권 구매 상담', '예약완료', '할인 문의');
INSERT INTO INQUIRY_RESERVE VALUES (SEQ_INQUIRY_NO.NEXTVAL, 3, 1, SYSDATE+2, '락커 이용 문의', '완료', '방문 완료');
INSERT INTO INQUIRY_RESERVE VALUES (SEQ_INQUIRY_NO.NEXTVAL, 3, 2, SYSDATE+15, 'GX 프로그램 안내', '예약완료', '요가 수업 희망');
INSERT INTO INQUIRY_RESERVE VALUES (SEQ_INQUIRY_NO.NEXTVAL, 4, 3, SYSDATE+12, '재등록 상담', '대기중', NULL);
INSERT INTO INQUIRY_RESERVE VALUES (SEQ_INQUIRY_NO.NEXTVAL, 4, 4, SYSDATE+20, '운동 기구 사용법', '예약완료', '초보자 가이드 필요');

-- 17. ATTENDANCE (출석) - 모든 필드 NOT NULL
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE_NO.NEXTVAL, 1, 1, '입실', SYSDATE-5);
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE_NO.NEXTVAL, 1, 1, '퇴실', SYSDATE-5);
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE_NO.NEXTVAL, 1, 2, '입실', SYSDATE-4);
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE_NO.NEXTVAL, 1, 2, '퇴실', SYSDATE-4);
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE_NO.NEXTVAL, 2, 3, '입실', SYSDATE-3);
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE_NO.NEXTVAL, 2, 3, '퇴실', SYSDATE-3);
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE_NO.NEXTVAL, 3, 4, '입실', SYSDATE-2);
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE_NO.NEXTVAL, 3, 4, '퇴실', SYSDATE-2);

-- 18. PURCHASE (구매) - PURCHASE_NO, MEMBER_NO, GYM_NO만 NOT NULL
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE_NO.NEXTVAL, 1, 1, SYSDATE-90, 100000, '결제');
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE_NO.NEXTVAL, 2, 1, SYSDATE-85, 270000, '결제');
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE_NO.NEXTVAL, 3, 2, SYSDATE-80, 400000, '결제');
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE_NO.NEXTVAL, 4, 3, SYSDATE-75, 1000000, '결제');
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE_NO.NEXTVAL, 1, 1, SYSDATE-70, 530000, '결제');
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE_NO.NEXTVAL, 2, 2, SYSDATE-65, 900000, '결제');
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE_NO.NEXTVAL, 3, 3, SYSDATE-60, 110000, '취소');
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE_NO.NEXTVAL, 4, 4, SYSDATE-55, 280000, '환불');

-- ============================================
-- 6단계: PURCHASE 자식 테이블들
-- ============================================

-- 19. PURCHASE_ITEM (구매아이템) - PURCHASE_ITEM_NO, MEMBERSHIP_PERIOD, PURCHASE_NO만 NOT NULL
INSERT INTO PURCHASE_ITEM VALUES (SEQ_PURCHASE_ITEM_NO.NEXTVAL, 30, NULL, NULL, SYSDATE-90, SYSDATE-60, 1);
INSERT INTO PURCHASE_ITEM VALUES (SEQ_PURCHASE_ITEM_NO.NEXTVAL, 90, NULL, NULL, SYSDATE-85, SYSDATE+5, 2);
INSERT INTO PURCHASE_ITEM VALUES (SEQ_PURCHASE_ITEM_NO.NEXTVAL, 30, 30, NULL, SYSDATE-80, SYSDATE-50, 3);
INSERT INTO PURCHASE_ITEM VALUES (SEQ_PURCHASE_ITEM_NO.NEXTVAL, 365, NULL, NULL, SYSDATE-75, SYSDATE+290, 4);
INSERT INTO PURCHASE_ITEM VALUES (SEQ_PURCHASE_ITEM_NO.NEXTVAL, 30, NULL, 10, SYSDATE-70, SYSDATE-40, 5);
INSERT INTO PURCHASE_ITEM VALUES (SEQ_PURCHASE_ITEM_NO.NEXTVAL, 90, NULL, 20, SYSDATE-65, SYSDATE+25, 6);
INSERT INTO PURCHASE_ITEM VALUES (SEQ_PURCHASE_ITEM_NO.NEXTVAL, 30, NULL, NULL, SYSDATE-60, SYSDATE-30, 7);
INSERT INTO PURCHASE_ITEM VALUES (SEQ_PURCHASE_ITEM_NO.NEXTVAL, 90, NULL, NULL, SYSDATE-55, SYSDATE+35, 8);

-- 20. MEMBERSHIP (회원권) - MEMBERSHIP_NO, PURCHASE_NO, MEMBER_NO, GYM_NO만 NOT NULL
INSERT INTO MEMBERSHIP VALUES (SEQ_MEMBERSHIP_NO.NEXTVAL, 1, 1, 1, SYSDATE-90, SYSDATE-60, '만료', SYSDATE-90, SYSDATE-60);
INSERT INTO MEMBERSHIP VALUES (SEQ_MEMBERSHIP_NO.NEXTVAL, 2, 2, 1, SYSDATE-85, SYSDATE+5, '정상', SYSDATE-85, SYSDATE-85);
INSERT INTO MEMBERSHIP VALUES (SEQ_MEMBERSHIP_NO.NEXTVAL, 3, 3, 2, SYSDATE-80, SYSDATE-50, '만료', SYSDATE-80, SYSDATE-50);
INSERT INTO MEMBERSHIP VALUES (SEQ_MEMBERSHIP_NO.NEXTVAL, 4, 4, 3, SYSDATE-75, SYSDATE+290, '정상', SYSDATE-75, SYSDATE-75);
INSERT INTO MEMBERSHIP VALUES (SEQ_MEMBERSHIP_NO.NEXTVAL, 5, 1, 1, SYSDATE-70, SYSDATE-40, '만료', SYSDATE-70, SYSDATE-40);
INSERT INTO MEMBERSHIP VALUES (SEQ_MEMBERSHIP_NO.NEXTVAL, 6, 2, 2, SYSDATE-65, SYSDATE+25, '정상', SYSDATE-65, SYSDATE-65);
INSERT INTO MEMBERSHIP VALUES (SEQ_MEMBERSHIP_NO.NEXTVAL, 7, 3, 3, SYSDATE-60, SYSDATE-30, '중단', SYSDATE-60, SYSDATE-60);
INSERT INTO MEMBERSHIP VALUES (SEQ_MEMBERSHIP_NO.NEXTVAL, 8, 4, 4, SYSDATE-55, SYSDATE+35, '환불', SYSDATE-55, SYSDATE-55);

-- 21. PT_PASS (PT이용권) - MEMBERSHIP_NO, PURCHASE_NO, MEMBER_NO, GYM_NO만 NOT NULL
INSERT INTO PT_PASS VALUES (SEQ_PT_PASS_NO.NEXTVAL, 5, 1, 1, SYSDATE-70, SYSDATE-40, 5, 10);
INSERT INTO PT_PASS VALUES (SEQ_PT_PASS_NO.NEXTVAL, 6, 2, 2, SYSDATE-65, SYSDATE+25, 8, 20);
INSERT INTO PT_PASS VALUES (SEQ_PT_PASS_NO.NEXTVAL, 5, 1, 1, SYSDATE-60, SYSDATE-30, 10, 10);
INSERT INTO PT_PASS VALUES (SEQ_PT_PASS_NO.NEXTVAL, 6, 2, 2, SYSDATE-55, SYSDATE+35, 3, 20);
INSERT INTO PT_PASS VALUES (SEQ_PT_PASS_NO.NEXTVAL, 5, 3, 2, SYSDATE-50, SYSDATE-20, 7, 10);
INSERT INTO PT_PASS VALUES (SEQ_PT_PASS_NO.NEXTVAL, 6, 4, 3, SYSDATE-45, SYSDATE+45, 2, 20);
INSERT INTO PT_PASS VALUES (SEQ_PT_PASS_NO.NEXTVAL, 5, 3, 2, SYSDATE-40, SYSDATE-10, 9, 10);
INSERT INTO PT_PASS VALUES (SEQ_PT_PASS_NO.NEXTVAL, 6, 4, 3, SYSDATE-35, SYSDATE+55, 5, 20);

-- 22. LOCKER_PASS (락커이용권) - LOCKER_PASS_NO, PURCHASE_NO, LOCKER_NO, MEMBER_NO만 NOT NULL
INSERT INTO LOCKER_PASS VALUES (SEQ_LOCKER_PASS_NO.NEXTVAL, 3, 2, 1, SYSDATE-80, SYSDATE-50, '만료');
INSERT INTO LOCKER_PASS VALUES (SEQ_LOCKER_PASS_NO.NEXTVAL, 3, 4, 2, SYSDATE-75, SYSDATE-45, '정상');
INSERT INTO LOCKER_PASS VALUES (SEQ_LOCKER_PASS_NO.NEXTVAL, 3, 6, 3, SYSDATE-70, SYSDATE-40, '만료');
INSERT INTO LOCKER_PASS VALUES (SEQ_LOCKER_PASS_NO.NEXTVAL, 3, 8, 4, SYSDATE-65, SYSDATE-35, '정상');
INSERT INTO LOCKER_PASS VALUES (SEQ_LOCKER_PASS_NO.NEXTVAL, 5, 2, 5, SYSDATE-60, SYSDATE-30, '만료');
INSERT INTO LOCKER_PASS VALUES (SEQ_LOCKER_PASS_NO.NEXTVAL, 6, 4, 6, SYSDATE-55, SYSDATE-25, '정상');
INSERT INTO LOCKER_PASS VALUES (SEQ_LOCKER_PASS_NO.NEXTVAL, 7, 6, 7, SYSDATE-50, SYSDATE-20, '만료');
INSERT INTO LOCKER_PASS VALUES (SEQ_LOCKER_PASS_NO.NEXTVAL, 8, 8, 8, SYSDATE-45, SYSDATE-15, '정상');

-- ============================================
-- 7단계: PT_PASS 자식 테이블
-- ============================================

-- 23. PT_RESERVE (PT예약) - PT_RESERVE_NO, PT_PASS_NO, TRAINER_MEMBER_NO만 NOT NULL
INSERT INTO PT_RESERVE VALUES (SEQ_PT_RESERVE_NO.NEXTVAL, 1, SYSDATE-65, '이코치', 5, null);
INSERT INTO PT_RESERVE VALUES (SEQ_PT_RESERVE_NO.NEXTVAL, 1, SYSDATE-60, '이코치', 5, null);
INSERT INTO PT_RESERVE VALUES (SEQ_PT_RESERVE_NO.NEXTVAL, 2, SYSDATE-55, '최트레이너', 6, null);
INSERT INTO PT_RESERVE VALUES (SEQ_PT_RESERVE_NO.NEXTVAL, 2, SYSDATE-50, '최트레이너', 6, null);
INSERT INTO PT_RESERVE VALUES (SEQ_PT_RESERVE_NO.NEXTVAL, 4, SYSDATE-45, '최트레이너', 6, null);
INSERT INTO PT_RESERVE VALUES (SEQ_PT_RESERVE_NO.NEXTVAL, 6, SYSDATE-40, '이코치', 5, null);
INSERT INTO PT_RESERVE VALUES (SEQ_PT_RESERVE_NO.NEXTVAL, 8, SYSDATE-35, '최트레이너', 6, null);
INSERT INTO PT_RESERVE VALUES (SEQ_PT_RESERVE_NO.NEXTVAL, 8, SYSDATE+5, '최트레이너', 6, null);

-- 24. SALES (매출) - SALES_NO, PURCHASE_NO, STOCK_ID, GYM_NO만 NOT NULL
INSERT INTO SALES VALUES (SEQ_SALES_NO.NEXTVAL, 1, 1, 1, '회원권', SYSDATE-90);
INSERT INTO SALES VALUES (SEQ_SALES_NO.NEXTVAL, 2, 2, 1, '회원권', SYSDATE-85);
INSERT INTO SALES VALUES (SEQ_SALES_NO.NEXTVAL, 3, 3, 2, '락커', SYSDATE-80);
INSERT INTO SALES VALUES (SEQ_SALES_NO.NEXTVAL, 4, 4, 3, '회원권', SYSDATE-75);
INSERT INTO SALES VALUES (SEQ_SALES_NO.NEXTVAL, 5, 5, 1, 'PT', SYSDATE-70);
INSERT INTO SALES VALUES (SEQ_SALES_NO.NEXTVAL, 6, 6, 2, 'PT', SYSDATE-65);
INSERT INTO SALES VALUES (SEQ_SALES_NO.NEXTVAL, 7, 7, 3, '회원권', SYSDATE-60);
INSERT INTO SALES VALUES (SEQ_SALES_NO.NEXTVAL, 8, 8, 4, '회원권', SYSDATE-55);

-- ============================================
-- COMMIT
-- ============================================
COMMIT;

-- ============================================
-- 데이터 확인 쿼리
-- ============================================
SELECT '=== GymHub 더미 데이터 삽입 완료 ===' AS INFO FROM DUAL;
SELECT '' AS BLANK FROM DUAL;
SELECT '총 테이블 수: 24개' AS INFO FROM DUAL;
SELECT '각 테이블당 8건씩 데이터 생성' AS INFO FROM DUAL;
SELECT '' AS BLANK FROM DUAL;

SELECT 'GOAL: ' || COUNT(*) || '건' AS DATA_COUNT FROM GOAL
UNION ALL
SELECT 'ATT_CACHE: ' || COUNT(*) || '건' FROM ATT_CACHE
UNION ALL
SELECT 'STOCK: ' || COUNT(*) || '건' FROM STOCK
UNION ALL
SELECT 'GYM: ' || COUNT(*) || '건' FROM GYM
UNION ALL
SELECT 'GYM_DETAIL: ' || COUNT(*) || '건' FROM GYM_DETAIL
UNION ALL
SELECT 'YOUTUBE_URL: ' || COUNT(*) || '건' FROM YOUTUBE_URL
UNION ALL
SELECT 'GYM_NOTICE: ' || COUNT(*) || '건' FROM GYM_NOTICE
UNION ALL
SELECT 'MACHINE: ' || COUNT(*) || '건' FROM MACHINE
UNION ALL
SELECT 'MACHINE_MANAGE: ' || COUNT(*) || '건' FROM MACHINE_MANAGE
UNION ALL
SELECT 'LOCKER: ' || COUNT(*) || '건' FROM LOCKER
UNION ALL
SELECT 'STOCK_MANAGER: ' || COUNT(*) || '건' FROM STOCK_MANAGER
UNION ALL
SELECT 'PRODUCT: ' || COUNT(*) || '건' FROM PRODUCT
UNION ALL
SELECT 'MEMBER: ' || COUNT(*) || '건' FROM MEMBER
UNION ALL
SELECT 'GOAL_MANAGE: ' || COUNT(*) || '건' FROM GOAL_MANAGE
UNION ALL
SELECT 'INBODY_RECORD: ' || COUNT(*) || '건' FROM INBODY_RECORD
UNION ALL
SELECT 'INQUIRY_RESERVE: ' || COUNT(*) || '건' FROM INQUIRY_RESERVE
UNION ALL
SELECT 'ATTENDANCE: ' || COUNT(*) || '건' FROM ATTENDANCE
UNION ALL
SELECT 'PURCHASE: ' || COUNT(*) || '건' FROM PURCHASE
UNION ALL
SELECT 'PURCHASE_ITEM: ' || COUNT(*) || '건' FROM PURCHASE_ITEM
UNION ALL
SELECT 'MEMBERSHIP: ' || COUNT(*) || '건' FROM MEMBERSHIP
UNION ALL
SELECT 'PT_PASS: ' || COUNT(*) || '건' FROM PT_PASS
UNION ALL
SELECT 'LOCKER_PASS: ' || COUNT(*) || '건' FROM LOCKER_PASS
UNION ALL
SELECT 'PT_RESERVE: ' || COUNT(*) || '건' FROM PT_RESERVE
UNION ALL
SELECT 'SALES: ' || COUNT(*) || '건' FROM SALES;

SELECT '' AS BLANK FROM DUAL;
SELECT '=== 회원 유형별 통계 ===' AS INFO FROM DUAL;
SELECT 
    CASE MEMBER_TYPE 
        WHEN 1 THEN '일반회원'
        WHEN 2 THEN '트레이너'
        WHEN 3 THEN '운영자'
    END AS 회원유형,
    COUNT(*) AS 인원수
FROM MEMBER
GROUP BY MEMBER_TYPE
ORDER BY MEMBER_TYPE;

SELECT '' AS BLANK FROM DUAL;
SELECT '=== 헬스장별 회원 수 ===' AS INFO FROM DUAL;
SELECT 
    G.GYM_NAME AS 헬스장명,
    COUNT(M.MEMBER_NO) AS 회원수
FROM GYM G
LEFT JOIN MEMBER M ON G.GYM_NO = M.GYM_NO
WHERE M.MEMBER_TYPE = 1
GROUP BY G.GYM_NAME
ORDER BY COUNT(M.MEMBER_NO) DESC;

-- 외래키 제약조건 삭제 (제약조건 이름 확인 필요)
ALTER TABLE SALES DROP CONSTRAINT FK_SALES_STOCK;

-- STOCK_ID를 NULL 허용으로 변경
ALTER TABLE SALES MODIFY STOCK_ID NULL;

-- 외래키 제약조건 재추가 (NULL 허용)
ALTER TABLE SALES ADD CONSTRAINT FK_SALES_STOCK 
    FOREIGN KEY (STOCK_ID) REFERENCES STOCK(STOCK_ID);

-- STOCK_MANAGER 테이블에 STOCK_MANAGE_COUNT 컬럼 추가
ALTER TABLE STOCK_MANAGER 
ADD STOCK_MANAGE_COUNT NUMBER;

-- 컬럼에 코멘트 추가 (선택사항)
COMMENT ON COLUMN STOCK_MANAGER.STOCK_MANAGE_COUNT IS '재고관리수량';

ALTER TABLE PT_RESERVE
    RENAME COLUMN PT_HOPE_TRAINER TO PT_TRAINER;
ALTER TABLE PT_RESERVE
    ADD PT_RESERVE_STATUS VARCHAR2(2);
COMMENT ON COLUMN PT_RESERVE.PT_TRAINER IS 'PT트레이너';
ALTER TABLE PT_RESERVE
    MODIFY PT_RESERVE_STATUS VARCHAR2(9);


TRUNCATE TABLE PT_RESERVE;
ALTER TABLE PT_RESERVE
    MODIFY PT_TRAINER NUMBER;
-- 3. 컬럼 설명 업데이트
COMMENT ON COLUMN PT_RESERVE.PT_TRAINER IS '희망 및 배정 트레이너 회원번호';

INSERT INTO PT_RESERVE (
    PT_RESERVE_NO,
    PT_PASS_NO,
    PT_RESERVE_TIME,
    PT_TRAINER,
    TRAINER_MEMBER_NO,
    PT_RESERVE_STATUS
)
VALUES (
    SEQ_PT_RESERVE_NO.NEXTVAL,
    (SELECT PT_PASS_NO FROM (
        SELECT PT_PASS_NO FROM PT_PASS 
        WHERE MEMBER_NO = 10 AND GYM_NO = 9 
        ORDER BY PT_PASS_NO DESC
    ) WHERE ROWNUM = 1),
    SYSDATE + 3,  -- 3일 후 예약
    13,  -- 희망 트레이너
    13,  -- 임시 배정 트레이너 (대기중이지만 NOT NULL 제약 때문에)
    '대기중'
);

-- 회원 11번의 PT 예약 (대기중)
INSERT INTO PT_RESERVE (
    PT_RESERVE_NO,
    PT_PASS_NO,
    PT_RESERVE_TIME,
    PT_TRAINER,
    TRAINER_MEMBER_NO,
    PT_RESERVE_STATUS
)
VALUES (
    SEQ_PT_RESERVE_NO.NEXTVAL,
    (SELECT PT_PASS_NO FROM (
        SELECT PT_PASS_NO FROM PT_PASS 
        WHERE MEMBER_NO = 11 AND GYM_NO = 9 
        ORDER BY PT_PASS_NO DESC
    ) WHERE ROWNUM = 1),
    SYSDATE + 5,  -- 5일 후 예약
    13,  -- 희망 트레이너
    13,  -- 임시 배정 트레이너
    '대기중'
);

-- 회원 12번의 PT 예약 (대기중)
INSERT INTO PT_RESERVE (
    PT_RESERVE_NO,
    PT_PASS_NO,
    PT_RESERVE_TIME,
    PT_TRAINER,
    TRAINER_MEMBER_NO,
    PT_RESERVE_STATUS
)
VALUES (
    SEQ_PT_RESERVE_NO.NEXTVAL,
    (SELECT PT_PASS_NO FROM (
        SELECT PT_PASS_NO FROM PT_PASS 
        WHERE MEMBER_NO = 12 AND GYM_NO = 9 
        ORDER BY PT_PASS_NO DESC
    ) WHERE ROWNUM = 1),
    SYSDATE + 7,  -- 7일 후 예약
    13,  -- 희망 트레이너
    13,  -- 임시 배정 트레이너
    '대기중'
);

-- 추가: 승인된 예약도 하나 만들어보기 (회원 10번)
INSERT INTO PT_RESERVE (
    PT_RESERVE_NO,
    PT_PASS_NO,
    PT_RESERVE_TIME,
    PT_TRAINER,
    TRAINER_MEMBER_NO,
    PT_RESERVE_STATUS
)
VALUES (
    SEQ_PT_RESERVE_NO.NEXTVAL,
    (SELECT PT_PASS_NO FROM (
        SELECT PT_PASS_NO FROM PT_PASS 
        WHERE MEMBER_NO = 10 AND GYM_NO = 9 
        ORDER BY PT_PASS_NO DESC
    ) WHERE ROWNUM = 1),
    SYSDATE + 10,  -- 10일 후 예약
    13,  -- 희망 트레이너
    13,  -- 배정 트레이너
    '승인됨'
);

-- 추가: 거절된 예약도 하나 만들어보기 (회원 11번)
INSERT INTO PT_RESERVE (
    PT_RESERVE_NO,
    PT_PASS_NO,
    PT_RESERVE_TIME,
    PT_TRAINER,
    TRAINER_MEMBER_NO,
    PT_RESERVE_STATUS
)
VALUES (
    SEQ_PT_RESERVE_NO.NEXTVAL,
    (SELECT PT_PASS_NO FROM (
        SELECT PT_PASS_NO FROM PT_PASS 
        WHERE MEMBER_NO = 11 AND GYM_NO = 9 
        ORDER BY PT_PASS_NO DESC
    ) WHERE ROWNUM = 1),
    SYSDATE + 12,  -- 12일 후 예약
    13,  -- 희망 트레이너
    13,  -- 임시 배정 트레이너
    '거절됨'
);

COMMIT;

ALTER TABLE PT_RESERVE
    RENAME COLUMN TRAINER_MEMBER_NO TO PT_TRAINER_NO;
COMMENT ON COLUMN PT_RESERVE.MEMBER_NO IS '희망트레이너, 트레이너 권한 회원';
    COMMENT ON COLUMN PT_RESERVE.PT_TRAINER_NO IS '승인된 트레이너 번호';
    COMMENT ON COLUMN PT_RESERVE.PT_RESERVE_STATUS IS '대기중, 승인됨, 거절됨';
COMMIT;