-- ========================================
-- PT 예약 기능 테스트용 데이터 (간단 버전)
-- PURCHASE_ITEM 없이 PT_PASS만 생성
-- ========================================

-- 각 회원에게 PT 이용권 생성
DECLARE
    v_member1_no NUMBER;
    v_member2_no NUMBER;
    v_member3_no NUMBER;
    v_purchase_no NUMBER;
BEGIN
    -- 회원 번호 조회
    SELECT MEMBER_NO INTO v_member1_no FROM MEMBER WHERE MEMBER_ID = 'testmember1';
    SELECT MEMBER_NO INTO v_member2_no FROM MEMBER WHERE MEMBER_ID = 'testmember2';
    SELECT MEMBER_NO INTO v_member3_no FROM MEMBER WHERE MEMBER_ID = 'testmember3';
    
    -- 회원1 PT 이용권
    INSERT INTO PURCHASE (PURCHASE_NO, MEMBER_NO, GYM_NO, PURCHASE_DATE, PURCHASE_COST, PURCHASE_STATUS)
    VALUES (SEQ_PURCHASE_NO.NEXTVAL, v_member1_no, 9, SYSDATE - 10, 500000, 'Y')
    RETURNING PURCHASE_NO INTO v_purchase_no;
    
    INSERT INTO PT_PASS (PT_PASS_NO, PURCHASE_NO, MEMBER_NO, GYM_NO, PT_START, PT_END, PT_USED_COUNT, PT_TOTAL_COUNT)
    VALUES (SEQ_PT_PASS_NO.NEXTVAL, v_purchase_no, v_member1_no, 9, SYSDATE - 10, SYSDATE + 80, 0, 10);
    
    -- 회원2 PT 이용권
    INSERT INTO PURCHASE (PURCHASE_NO, MEMBER_NO, GYM_NO, PURCHASE_DATE, PURCHASE_COST, PURCHASE_STATUS)
    VALUES (SEQ_PURCHASE_NO.NEXTVAL, v_member2_no, 9, SYSDATE - 5, 500000, 'Y')
    RETURNING PURCHASE_NO INTO v_purchase_no;
    
    INSERT INTO PT_PASS (PT_PASS_NO, PURCHASE_NO, MEMBER_NO, GYM_NO, PT_START, PT_END, PT_USED_COUNT, PT_TOTAL_COUNT)
    VALUES (SEQ_PT_PASS_NO.NEXTVAL, v_purchase_no, v_member2_no, 9, SYSDATE - 5, SYSDATE + 85, 0, 10);
    
    -- 회원3 PT 이용권
    INSERT INTO PURCHASE (PURCHASE_NO, MEMBER_NO, GYM_NO, PURCHASE_DATE, PURCHASE_COST, PURCHASE_STATUS)
    VALUES (SEQ_PURCHASE_NO.NEXTVAL, v_member3_no, 9, SYSDATE - 3, 500000, 'Y')
    RETURNING PURCHASE_NO INTO v_purchase_no;
    
    INSERT INTO PT_PASS (PT_PASS_NO, PURCHASE_NO, MEMBER_NO, GYM_NO, PT_START, PT_END, PT_USED_COUNT, PT_TOTAL_COUNT)
    VALUES (SEQ_PT_PASS_NO.NEXTVAL, v_purchase_no, v_member3_no, 9, SYSDATE - 3, SYSDATE + 87, 0, 10);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('회원 3명의 PT 이용권 생성 완료');
END;
/

-- trainer (MEMBER_NO=10)의 2025-11-22 예약 3개 추가
DECLARE
    v_trainer_no NUMBER := 10;
    v_member1_no NUMBER;
    v_member2_no NUMBER;
    v_member3_no NUMBER;
    v_pt_pass1_no NUMBER;
    v_pt_pass2_no NUMBER;
    v_pt_pass3_no NUMBER;
BEGIN
    SELECT MEMBER_NO INTO v_member1_no FROM MEMBER WHERE MEMBER_ID = 'testmember1';
    SELECT MEMBER_NO INTO v_member2_no FROM MEMBER WHERE MEMBER_ID = 'testmember2';
    SELECT MEMBER_NO INTO v_member3_no FROM MEMBER WHERE MEMBER_ID = 'testmember3';
    
    SELECT PT_PASS_NO INTO v_pt_pass1_no FROM PT_PASS WHERE MEMBER_NO = v_member1_no AND ROWNUM = 1;
    SELECT PT_PASS_NO INTO v_pt_pass2_no FROM PT_PASS WHERE MEMBER_NO = v_member2_no AND ROWNUM = 1;
    SELECT PT_PASS_NO INTO v_pt_pass3_no FROM PT_PASS WHERE MEMBER_NO = v_member3_no AND ROWNUM = 1;
    
    INSERT INTO PT_RESERVE (PT_RESERVE_NO, PT_PASS_NO, PT_RESERVE_TIME, MEMBER_NO, PT_TRAINER_NO, PT_RESERVE_STATUS)
    VALUES (SEQ_PT_RESERVE_NO.NEXTVAL, v_pt_pass1_no, TO_DATE('2025-11-22 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), v_trainer_no, v_trainer_no, '승인됨');
    
    INSERT INTO PT_RESERVE (PT_RESERVE_NO, PT_PASS_NO, PT_RESERVE_TIME, MEMBER_NO, PT_TRAINER_NO, PT_RESERVE_STATUS)
    VALUES (SEQ_PT_RESERVE_NO.NEXTVAL, v_pt_pass2_no, TO_DATE('2025-11-22 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), v_trainer_no, v_trainer_no, '승인됨');
    
    INSERT INTO PT_RESERVE (PT_RESERVE_NO, PT_PASS_NO, PT_RESERVE_TIME, MEMBER_NO, PT_TRAINER_NO, PT_RESERVE_STATUS)
    VALUES (SEQ_PT_RESERVE_NO.NEXTVAL, v_pt_pass3_no, TO_DATE('2025-11-22 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), v_trainer_no, v_trainer_no, '승인됨');
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('trainer(MEMBER_NO=10)의 2025-11-22 예약 3개 추가 완료 (10:00, 14:00, 18:00)');
END;
/

-- 확인 쿼리
SELECT PP.PT_PASS_NO, PP.MEMBER_NO, M.MEMBER_NAME, PP.PT_TOTAL_COUNT, PP.PT_USED_COUNT
FROM PT_PASS PP
JOIN MEMBER M ON PP.MEMBER_NO = M.MEMBER_NO
WHERE M.MEMBER_ID IN ('testmember1', 'testmember2', 'testmember3')
ORDER BY PP.PT_PASS_NO;

SELECT 
    PR.PT_RESERVE_NO,
    TO_CHAR(PR.PT_RESERVE_TIME, 'YYYY-MM-DD HH24:MI') AS RESERVE_TIME,
    M_RESERVING.MEMBER_NAME AS RESERVING_MEMBER,
    M_TRAINER.MEMBER_NAME AS TRAINER_NAME,
    PR.PT_RESERVE_STATUS
FROM PT_RESERVE PR
JOIN PT_PASS PP ON PR.PT_PASS_NO = PP.PT_PASS_NO
JOIN MEMBER M_RESERVING ON PP.MEMBER_NO = M_RESERVING.MEMBER_NO
JOIN MEMBER M_TRAINER ON PR.PT_TRAINER_NO = M_TRAINER.MEMBER_NO
WHERE PR.PT_TRAINER_NO = 10
  AND TO_CHAR(PR.PT_RESERVE_TIME, 'YYYY-MM-DD') = '2025-11-22'
ORDER BY PR.PT_RESERVE_TIME;

COMMIT;

